-- testkit/test_prose.lua — the US-English prose gate (localization-§5), over every file git tracks.
--
-- WHAT IT PROVES. That no authored file this repository tracks carries a British spelling from
-- localization-§5's published `BRITISH` list, once the `ALLOWED` US words that contain one of those
-- substrings have been taken out as whole words. Source, locale files, the TOC, `README.md` and
-- every document under `docs/` — the whole authored set, read from git.
--
-- IT SHIPS IN THE KIT, so a consumer inherits it instead of writing its own. Seven repositories had
-- written this gate by hand before it was, under three different file names, and four more had
-- none: a rule enforced by eleven hand-written copies is eleven chances to carry a subset. A
-- REPOSITORY WITH ITS OWN COPY WIRES ONE OR THE OTHER, NEVER BOTH.
--
-- It takes the kit as its chunk argument rather than reading the exposed table, for the reason
-- `test_eol.lua` does: that table's global name belongs to the consumer (`LK_TEST`, `AT_TEST`,
-- …) and a vendored suite cannot know which one it is standing in. Wire it as
-- `{ name = "test_prose", dir = "tests/_kit/" }` in the runner's suite list; the suite inventory
-- goes red until you do, so it cannot arrive with a re-vendor and then quietly run nothing.
--
-- BOTH LISTS ARE COPIED WHOLE, AND NOTHING IS ADDED. localization-§5 is explicit that a gate MUST
-- carry every `BRITISH` and `ALLOWED` entry and MUST NOT carry one the section does not publish: a
-- private list is a coverage claim no reader outside the repo can check. A British form the
-- published list misses is amended in the standard first and arrives here on the next sync.
--
-- THE GENERATED-DATA CARVE-OUT, AND WHY IT ARRIVES THROUGH THE OPTS TABLE. `layout-§1` settled this
-- exact question one revision earlier for the 1500-line cap, and the reasoning transfers whole. A
-- generated dump of the client's own strings is not this repository's English: it is Blizzard's,
-- regenerated by a script, and localization-§5 names it as the third shape a spelling may
-- legitimately carry here. It stands on three conditions, all ABOUT THE REPOSITORY —
--
--   * GENERATED rather than authored: a script writes it and a person does not edit it;
--   * LOADED BY NOTHING: no TOC line, no `dofile`, no runtime reader;
--   * EXCLUDED FROM WHAT A PLAYER DOWNLOADS: `.pkgmeta` keeps it out of the packaged zip.
--
-- — and no path betrays any of the three, so the exempt set ARRIVES THROUGH THE OPTS TABLE the way
-- `Kit.layoutCap.exempt` does, and nothing about a particular repository is compiled in here: a
-- reader who knows one gate knows both.
--
-- TWO OF THE THREE ARE GATED, AND THE FIRST DRAFT GATED NONE OF THEM. A path betrays nothing, but
-- the repository ROOT this gate runs in answers two of them out loud, and reading them is the
-- difference between a carve-out and the whole-file waiver localization-§5 forbids. Measured:
--
--   Kit.prose = { exempt = { "core/WhatGroup.lua", "docs/data-flow.md", "tests/" } }
--
-- WhatGroup's prose gate went GREEN, and `core\WhatGroup.lua` is line 48 of its TOC — five hits
-- suppressed, two of them inside the packaged payload, and the run printed not one word about it.
-- A carve-out that can swallow a shipped file is the escape the rule exists to close. So:
--
--   * A PATH THE TOC LOADS IS REFUSED. Every tracked `.toc` is parsed, its lines resolved against
--     its own folder and its backslashes read as the separators they are, and a declared narrowing
--     covering any of them reddens the run. It reads each TOC's OWN lines and nothing further: an
--     `.xml` line pulls in a tree of `.lua` the TOC never names, and a `dofile` inside a loaded
--     file pulls in more, so the rest of LOADED BY NOTHING stays with the auditor.
--
--   * A PATH `.pkgmeta` DOES NOT IGNORE IS REFUSED. The root `.pkgmeta`'s `ignore:` block is read,
--     and a narrowing no ignore entry covers reddens the run: if the packager puts it in the zip a
--     player downloads its spellings, which is the one thing this rule exists to prevent.
--
--   * WHERE THERE IS NO `.toc`, THE FIRST CHECK DEGRADES RATHER THAN DISAPPEARING: it SKIPS with
--     the reason printed rather than passing quietly, because a library or documentation repo has
--     no TOC for LOADED BY NOTHING to be read off, and a gate that goes green when it cannot look
--     is the failure this file is built against. Same for `.pkgmeta` where nothing is packaged;
--     but a `.toc` with NO `.pkgmeta` is refused, because the packager then ships the tree whole.
--
-- AND BOTH REFUSALS REACH BOTH CHANNELS, WHICH THE FIRST TWO DRAFTS DID NOT. There are two ways a
-- repository narrows this gate, and gating one of them is gating neither. `Kit.prose.exempt` in the
-- runner is the carve-out above; `skipDirs` and `skipFiles` in `tests/prose_waivers.lua` are the
-- named-exclusion list further down this file. They merge into the SAME exclusion sets and take
-- files out of the SAME scan, and until this revision they were checked against nothing at all --
-- while the refusal above pointed a consumer it had just refused straight at them. So every entry
-- in all three lists is a DECLARED NARROWING and both refusals run over the lot: what differs is
-- only what an entry MEANS to a reader, and no meaning survives the file being one that ships.
--
-- EACH CHANNEL IS REFUSED ON ITS OWN MATCHING RULE, never a shared one, AND BOTH REFUSALS READ ONE
-- RESOLVED COVERAGE SET. A `Kit.prose.exempt` entry covers a path or a folder, a `skipDirs` entry
-- is the plain prefix the scan compares, a `skipFiles` entry is one exact path -- matched more
-- loosely, a refusal would reject a narrowing that suppresses nothing; more tightly, it would wave
-- one through on the very file it does take out of the scan. Each entry is resolved through its OWN
-- rule ONCE and everything reads that one resolution, because resolving it apiece is how the two
-- refusals CAME TO DISAGREE ABOUT WHAT THEY REFUSED: packaging asked `.pkgmeta` about the entry AS
-- WRITTEN while the TOC asked about the paths it suppresses, and for an unanchored `skipDirs`
-- prefix checked against an `entry .. "/"` anchor those are different questions. Under a `.pkgmeta`
-- that ignores the `tools` folder, `skipDirs = { "tools" }` hid the shipped root file
-- `tools-notes.md` beside it with BOTH REFUSALS GREEN. Packaging therefore asks about the entry as
-- written AND about every path it covers: the first arm keeps a stale entry honest, the second
-- closes what it left open. An entry covering nothing is refused for its SPELLING instead, because
-- the packaging line would contradict the same run's disclosure.
--
-- THE KIT'S OWN EXCLUSIONS ARE NEITHER REFUSED NOR DISCLOSED. `libs/`, `tests/_kit/`,
-- `locales/enGB.lua` and the frozen dated bundles are localization-§5's published list, identical in
-- every repository and written down below; `libs/` is loaded by every TOC in the collection on
-- purpose. They are the baseline the disclosure measures FROM, not something this repository chose.
--
-- AND THE NARROWING IS DISCLOSED, IN ONE LINE COVERING BOTH CHANNELS. A passing case NAMES every
-- path this repository narrowed the gate by, says which of the three lists each came from, counts
-- the tracked authored files the lot of them suppressed AND NAMES THOSE FILES, grouped under the
-- entry that suppressed each. The count alone was what let a `.pkgmeta`-blessed entry over a
-- shipped file read as ratified rather than as suspicious: nothing tied the number to a file. The
-- list is BOUNDED and says so, because one entry can suppress hundreds and a truncated list a
-- reader takes for a complete one is worse than a count alone. The first draft printed nothing; the
-- second printed the carve-out alone, which is how the older and wider channel beside it went a
-- whole revision unexamined. That case and the two refusals register only where this repository
-- declared a narrowing of its own: an addon with no carve-out and no waiver file has nothing to
-- disclose, and three standing skips every run would be noise a reader learns to scroll past.
--
-- IT IS MEASURED, NOT HYPOTHETICAL. Without the carve-out this gate fails the one repository that
-- had already done everything the rule asked: PrettyChat tracks 27 generated `GlobalStrings/`
-- files, one of them 23,842 lines, and all 34 British spellings this gate reports there are
-- Blizzard constants or sentences. Its hand-written copy named the folder in its skip list and was
-- green; retiring it for this one, which testing-§9 requires, is what takes it red.
--
-- WHAT IT MUST NOT BECOME. localization-§5 forbids a whole-file waiver as a general escape — it
-- hides every OTHER British spelling in a file the repository edits often — and this carve-out
-- MUST NOT be one by the back door. An authored file somebody would rather not fix belongs in
-- `tests/prose_waivers.lua`'s `waived` table, per file AND per word, with the reason beside it:
-- the ONE narrowing the two refusals do not reach, because a waiver that has to name the word
-- cannot hide a spelling it did not name. Its SHAPE is still checked, in `validateWaived` below.
-- In particular: A GENERATED FILE THAT SHIPS IS NOT EXEMPT.
--
-- AND IT IS STILL NOT THE WAIVER FILE'S `skipDirs`, THOUGH THE TWO ARE NOW POLICED ALIKE. Those
-- answer localization-§5's own named-exclusion list — a frozen dated store this kit cannot know the
-- name of, a document whose subject is this rule — while the exempt set sits in `tests/run.lua`,
-- where an auditor already reads `Kit.layoutCap.exempt` naming the SAME folder for the SAME three
-- reasons. One consequence, stated rather than discovered in a red run: a British locale file
-- cannot be taken out by `skipFiles`, because it is TOC-loaded and shipped, so both refusals
-- reject it. `locales/enGB.lua` is excluded by name in the published list below.
--
-- THE THIRD CONDITION IS THE AUDITOR'S CALL AND NEVER THIS GATE'S, drawn where the cap gate draws
-- its equivalent. GENERATED RATHER THAN AUTHORED is a fact about how a file came to exist, and
-- nothing in the repository root records it, so the gate does not guess. A repository that puts a
-- hand-written file in the exempt set, past a TOC that does not load it and a `.pkgmeta` that
-- ignores it, has fooled the gate and will be caught by a reader — which is why the disclosure
-- exists: it puts that set, and the files it suppressed, in front of that reader every run.
--
-- WIRING, in the consumer's `tests/run.lua`, before `Kit.run`:
--
--   Kit.prose = { exempt = { "GlobalStrings/" } }   -- generated, loaded by nothing, not packaged
--
-- Optional, and absent is the normal case: ten of the eleven addons that vendor this kit have no
-- generated data. An entry is a tracked path, or a folder ending in `/`. The waiver file's
-- `skipDirs` and `skipFiles` are the other two lists a repository can narrow this gate by, and
-- every word above about the refusals and the disclosure applies to them unchanged.
--
-- IT FAILS RATHER THAN PASSES WHEN IT CANNOT LOOK. No `io.popen`, no git, an unreadable tracked file
-- — every one of those is a failure, not a skip. A gate that goes quiet when it is blind reports
-- success, which is worse than not existing. Same bargain `test_eol.lua` strikes.

local Kit = ...
local test, fail = Kit.test, Kit.fail

-- ---------------------------------------------------------------------------
-- The published lists (localization-§5), copied whole, and the folder exclusions
-- ---------------------------------------------------------------------------

-- In `prose_lists.lua` beside this file since kit revision 26, so that the lists can grow without
-- taking this gate past `layout-§1`'s cap. Found from this chunk's own name, the way `mock_base.lua`
-- finds `mock_record.lua`, with the vendored layout as the fallback. A missing file raises at load:
-- a gate with no list to read would pass every file it scans.
local function listsDir()
    local info = debug and debug.getinfo and debug.getinfo(1, "S")
    local dir = info and tostring(info.source or ""):match("^@(.*[/\\])")
    local f = dir and io.open(dir .. "prose_lists.lua", "r")
    if f then f:close(); return dir end
    return "tests/_kit/"
end

local LISTS = dofile(listsDir() .. "prose_lists.lua")
local BRITISH, ALLOWED = LISTS.BRITISH, LISTS.ALLOWED
local PUBLISHED_BRITISH, PUBLISHED_ALLOWED = LISTS.PUBLISHED_BRITISH, LISTS.PUBLISHED_ALLOWED
local SKIPPED_DIRS = LISTS.SKIPPED_DIRS

-- The store-root files read although a kit folder above covers them (`SCAN_BACK`, revision 26), and
-- the kit folders they are read back from. Sets, because `filterPaths` asks both per path.
local SCAN_BACK, KIT_DIRS = {}, {}
for _, path in ipairs(LISTS.SCAN_BACK) do SCAN_BACK[path] = true end
for _, dir in ipairs(SKIPPED_DIRS) do KIT_DIRS[dir] = true end

-- ---------------------------------------------------------------------------
-- What is scanned, and what is not
-- ---------------------------------------------------------------------------

-- The exclusions localization-§5 names, and only those. The folders are `SKIPPED_DIRS`, in
-- `prose_lists.lua` with the spellings, which also names in `SCAN_BACK` the three store-root files
-- read back out of them; the files are below. Every one is a directory or a file
-- rather than a pattern, so the list cannot quietly grow by widening a regex: `locales/enGB.lua`,
-- which is what a British locale file is for, and the gate itself, which quotes every forbidden
-- spelling in order to forbid it.
local SKIPPED_FILES = {
    ["locales/enGB.lua"] = true,
    ["tests/test_prose.lua"] = true,
    ["tests/test_spelling.lua"] = true,
    -- The waiver file is the fourth exclusion, for the same reason the gate is: every reason
    -- written beside a waiver is prose ABOUT a forbidden spelling, and a gate that scans it
    -- reddens on the file whose whole job is to record what it must not correct.
    ["tests/prose_waivers.lua"] = true,
}

-- ---------------------------------------------------------------------------
-- The narrowing machinery, in `prose_coverage.lua` beside this file
-- ---------------------------------------------------------------------------

-- Since kit revision 29 (issue #39): the consumer facts, a declared narrowing from any of the three
-- lists, the TOC and `.pkgmeta` readers, the one resolved coverage set and the two refusals that
-- read it. Moved unchanged, loaded from the folder `prose_lists.lua` is found in; a missing file
-- raises at load.
local COVERAGE = assert(loadfile(listsDir() .. "prose_coverage.lua"))(fail, SCAN_BACK, KIT_DIRS)
local validateOptions, resolveExempt = COVERAGE.validateOptions, COVERAGE.resolveExempt
local SOURCE_SKIPFILES, SOURCE_WAIVED = COVERAGE.SOURCE_SKIPFILES, COVERAGE.SOURCE_WAIVED
local dirCovers, waiverNarrowings, allNarrowings =
    COVERAGE.dirCovers, COVERAGE.waiverNarrowings, COVERAGE.allNarrowings
local tocLoads, pkgmetaIgnores = COVERAGE.tocLoads, COVERAGE.pkgmetaIgnores
local coverageOf, coverageSummary = COVERAGE.coverageOf, COVERAGE.coverageSummary
local narrowingsLoadedByToc, narrowingsNotIgnored =
    COVERAGE.narrowingsLoadedByToc, COVERAGE.narrowingsNotIgnored

local function options() return validateOptions(Kit.prose) end

--- The live carve-out, read the same way and at the same moment the gate reads it.
local function declared() return options().exempt end

-- ---------------------------------------------------------------------------
-- What the consumer adds: its own exclusions and its waivers
-- ---------------------------------------------------------------------------

--- The optional `tests/prose_waivers.lua`, which a consumer writes and this file reads.
---
--- WHY THIS SEAM EXISTS AT ALL, rather than the kit carrying the exceptions. Some British spellings
--- in a Ka0s tree are not the repository's English to correct, and the kit cannot know which:
--- AceTimer's flag field carries the British double-L spelling of *canceled* and a handle records
--- the flag under that name, because that is what `tests/_kit/mock_record.lua`'s live-timer survey
--- reads off it -- correct it and a stand-down suite's timer assertion goes quietly unfalsifiable.
--- Blizzard spells its `LFG_LIST_APPLICATION_STATUS_UPDATED` status the same way, and an addon
--- matches it verbatim off the event. localization-§5 already says to match game data on the token
--- the game uses; this is that rule meeting this gate. A GENERATED DUMP OF THE CLIENT'S OWN STRINGS
--- IS NOT ONE OF THESE and does not belong here: it is `Kit.prose.exempt` in the runner, beside
--- `Kit.layoutCap.exempt` naming the same folder.
---
--- THE SHAPE IS PER FILE AND PER WORD, never per file alone. A whole-file waiver hides every other
--- British spelling in a file the repo edits often, which is how a gate acquires a blind spot the
--- size of a module. Returning:
---
---     return {
---       skipDirs = { "docs/spell-research/" },        -- optional, named not patterned
---       skipFiles = { ["docs/vendor-notes.md"] = true },
---       waived = {
---         ["core/LifecycleSetup.lua"] = { ["cancel" .. "led"] = true },
---       },
---     }
---
--- `skipDirs` AND `skipFiles` EXTEND THE NAMED EXCLUSION LIST ABOVE, and nothing wider. They are
--- for the categories localization-§5 already names but this kit cannot spell for a consumer — a
--- frozen dated store under a name only that repo knows, a document whose subject is this rule --
--- and not a home for generated data: that is the opts-borne carve-out, in the runner.
---
--- AND THEY FACE THE SAME TWO REFUSALS `Kit.prose.exempt` DOES, over the same resolved coverage: an
--- entry a TOC loads is refused, and one `.pkgmeta` does not ignore -- as written, or for a file it
--- covers -- is refused, because whatever a reader means by the entry, a file inside the packaged
--- payload carries its spellings to a player's screen. They appear in the same disclosure too.
--- `waived` is the only list here not policed that way: it names the word, so it cannot hide one it
--- did not name. Its SHAPE is validated all the same, in `validateWaived` below.
---
--- ABSENT IS THE NORMAL CASE and means no waivers. A repo with nothing to waive ships no file.
local function consumerRules()
    local chunk = loadfile("tests/prose_waivers.lua")
    if not chunk then return {} end
    local ok, rules = pcall(chunk)
    if not ok or type(rules) ~= "table" then
        fail("prose gate: tests/prose_waivers.lua exists but did not return a table (" ..
            tostring(rules) .. "). A waiver file that cannot be read must not be treated as "
            .. "an empty one, because that silently widens the gate", 2)
    end
    return rules
end

--- `waived`, validated. The third key in the same table, and until now the only one with no
--- validation at all: a `waived` that was not a table died inside the scan with a raw Lua error
--- instead of this gate's own words, and the ARRAY FORMS -- `waived = { "core/Foo.lua" }`, or a
--- file's words written as `{ "cancel" .. "led" }` -- waived NOTHING and said nothing, because the
--- scan looks both up by key. That is the silence just removed from `skipFiles`, one key over.
---
--- IT IS POLICED FOR SHAPE HERE AND BY NOTHING ELSE, deliberately: `waived` stays outside the two
--- refusals because it is per FILE and per WORD, so it cannot hide a spelling it did not name --
--- which is why both refusals point at it as the way out. What it CAN do is waive nothing while
--- looking like a waiver.
local function validateWaived(waived)
    if waived == nil then return {} end
    if type(waived) ~= "table" then
        fail("prose gate: " .. SOURCE_WAIVED .. " maps a tracked path to the words waived in it, "
            .. "per file AND per word; this repository set it to a " .. type(waived), 3)
    end
    for path, words in pairs(waived) do
        if type(path) ~= "string" then
            fail("prose gate: " .. SOURCE_WAIVED .. " is KEYED by the path being waived; this key "
                .. "is a " .. type(path) .. ", so the array form waives nothing rather than "
                .. "saying so", 3)
        elseif type(words) ~= "table" then
            fail("prose gate: " .. SOURCE_WAIVED .. "'s entry for " .. path .. " is the set of "
                .. "words waived in that file, per WORD and never per file alone; this one is a "
                .. type(words) .. ", and a whole-file waiver is what localization-§5 forbids", 3)
        else
            for word in pairs(words) do
                if type(word) ~= "string" then
                    fail("prose gate: " .. SOURCE_WAIVED .. "'s entry for " .. path .. " is keyed "
                        .. "by the British spelling being waived, lowercase, as localization-§5 "
                        .. "publishes it; this key is a " .. type(word) .. ", so that array form "
                        .. "waives nothing either", 3)
                end
            end
        end
    end
    return waived
end

--- True when `path` is authored text this section has an opinion about.
---
--- Extension rather than directory, because the authored set is not one tree: locale values sit in
--- `locales/`, comments in `core/`, prose in `docs/` and the TOC's own notes at the root.
--- `.luacheckrc` is named on its own — it is authored Lua with authored comments wearing a different
--- extension, and an extension rule alone would miss it.
local function isAuthoredText(path)
    return path:find("%.lua$") or path:find("%.md$") or path:find("%.toc$") or path == ".luacheckrc"
end

--- Split a NUL-delimited blob. `git ls-files -z` because a path may contain anything but NUL, and
--- the line-oriented form quotes such a path instead of printing it — a quoted path would not open,
--- and this gate would then report a read failure that is really a parse failure.
local function splitNul(blob)
    local out, start = {}, 1
    while true do
        local i = blob:find("\0", start, true)
        if not i then break end
        if i > start then out[#out + 1] = blob:sub(start, i - 1) end
        start = i + 1
    end
    return out
end

--- The authored paths among `all`, minus the named exclusions and minus the exempt set, in order.
---
--- Pure, and separated from the git call below so the self-tests can drive it over a fixture list.
--- The exempt set drops the file outright rather than filtering its hits: a carved-out dump is
--- generated data the gate has no opinion about, and PrettyChat's is 1.6 MB it would read to say
--- nothing.
---
--- A `SCAN_BACK` file is kept against a kit folder, and against a repository `skipDirs` entry that
--- only restates one (`dirCovers`); a wider `skipDirs` entry, or `skipFiles`, still drops it.
local function hiddenByDir(path, skipDirs)
    for _, dir in ipairs(skipDirs) do
        if dirCovers(dir, path) then return true end
    end
    return false
end

local function filterPaths(all, skipFiles, skipDirs, exempt)
    local paths = {}
    for _, path in ipairs(all) do
        if isAuthoredText(path) and not skipFiles[path] and not exempt[path]
            and not hiddenByDir(path, skipDirs) then
            paths[#paths + 1] = path
        end
    end
    return paths
end

--- Every path `git ls-files` reports, read once and kept for the rest of the run.
---
--- Memoized because four readers want it — the scan, the two refusals and the disclosure, which
--- wants it while the suite is still LOADING to write its own case name. A failed read is never
--- cached, so blindness is reported every time rather than once. It is asked of the WHOLE tracked
--- set, before any filtering: an empty answer AFTER filtering has two causes with opposite
--- meanings — git said nothing, or a runner exempted everything — so each is reported as itself,
--- here and at the end of `scannedPaths`.
local trackedCache
local function trackedPaths()
    if trackedCache then return trackedCache end
    if not io.popen then
        fail("prose gate: io.popen is unavailable, so the tracked set cannot be read and this gate "
            .. "must not be reported as passing", 3)
    end
    local pipe = io.popen("git ls-files -z")
    if not pipe then
        fail("prose gate: io.popen returned no handle for `git ls-files`, so this gate cannot run "
            .. "and must not be reported as passing", 3)
    end
    local blob = pipe:read("*a") or ""
    pipe:close()

    local tracked = splitNul(blob)
    if #tracked == 0 then
        fail("prose gate: `git ls-files` reported no tracked files at all, which cannot be true -- "
            .. "either git is unavailable or this is not a repository; this gate cannot run, and "
            .. "must not be reported as passing", 3)
    end
    trackedCache = tracked
    return tracked
end

--- The body of `path`, or nil when it cannot be opened.
local function readFile(path)
    local fh = io.open(path, "r")
    if not fh then return nil end
    local body = fh:read("*a") or ""
    fh:close()
    return body
end

--- localization-§5's own named exclusions, as the two shapes `filterPaths` takes, and nothing else.
---
--- The baseline the disclosure measures FROM: the same in every repository, and `libs/` is loaded
--- by every TOC on purpose, so they are neither refused nor disclosed. What a repository ADDS is.
local function kitExclusionSets()
    local skipFiles = {}
    for k, v in pairs(SKIPPED_FILES) do skipFiles[k] = v end
    local skipDirs = {}
    for _, d in ipairs(SKIPPED_DIRS) do skipDirs[#skipDirs + 1] = d end
    return skipFiles, skipDirs
end

--- The named exclusions plus the consumer's, as the two shapes `filterPaths` takes.
---
--- Built from `waiverNarrowings`, the same reader the two refusals and the disclosure use. ONE
--- READER IS THE POINT: a scan that read `skipFiles` one way while the refusals read it another is
--- a narrowing policed in a shape nobody wrote. It also fixed a silence -- the array form
--- `skipFiles = { "docs/notes.md" }` was copied across key and all, leaving a numeric key no path
--- lookup could hit, so a consumer who wrote it excluded nothing and was told nothing.
local function exclusionSets(rules)
    local skipFiles, skipDirs = kitExclusionSets()
    for _, n in ipairs(waiverNarrowings(rules)) do
        if n.source == SOURCE_SKIPFILES then
            skipFiles[n.entry] = true
        else
            skipDirs[#skipDirs + 1] = n.entry
        end
    end
    return skipFiles, skipDirs
end

--- Every path every tracked `.toc` loads, and how many TOCs were read.
---
--- Zero TOCs is not a failure and not a silence either: the caller SKIPS with the reason, because
--- a repository that packages no addon has no TOC for LOADED BY NOTHING to be read off. A TOC git
--- tracks and this process cannot open IS a failure -- the gate going blind on the condition.
local function tocLoadedPaths()
    local loaded, count = {}, 0
    for _, path in ipairs(trackedPaths()) do
        if path:find("%.toc$") then
            count = count + 1
            local body = readFile(path)
            if body == nil then
                fail("prose gate: git tracks " .. path .. " but it cannot be opened, and it is "
                    .. "where the carve-out's LOADED BY NOTHING condition is read; this gate "
                    .. "cannot look and must not be reported as passing", 3)
            end
            for _, hit in ipairs(tocLoads(path, body)) do loaded[#loaded + 1] = hit end
        end
    end
    return loaded, count
end

--- Every authored path git tracks, minus the named exclusions and the carve-out, in git's order.
local function scannedPaths(rules, exemptEntries)
    local tracked = trackedPaths()
    local skipFiles, skipDirs = exclusionSets(rules)

    local paths = filterPaths(tracked, skipFiles, skipDirs, resolveExempt(exemptEntries, tracked))
    if #paths == 0 then
        fail("prose gate: git tracks " .. #tracked .. " file(s) and the exclusions and the "
            .. "carve-out between them removed every authored one, so this gate would read "
            .. "nothing and report green. Narrow `Kit.prose.exempt` in tests/run.lua, or the "
            .. "skipDirs or skipFiles in tests/prose_waivers.lua, until it reads the repository "
            .. "again -- the disclosure case names which of the three every path came from", 2)
    end
    return paths
end

--- The British substrings present in one line, after `ALLOWED` has been taken out as whole words.
---
--- Whole words, and before the scan, exactly as localization-§5 requires: delimit on non-letters,
--- drop a token that IS an allowance, run the substrings over what is left. Matching `ALLOWED` as a
--- substring would swallow *analysed* inside the allowance for *analyses*.
local ALLOWED_SET = {}
for _, word in ipairs(ALLOWED) do ALLOWED_SET[word] = true end

local function britishIn(line)
    local lowered = line:lower()
    local kept = lowered:gsub("%a+", function(token)
        if ALLOWED_SET[token] then return "" end
        return token
    end)

    local found
    for _, entry in ipairs(BRITISH) do
        if kept:find(entry, 1, true) then
            found = found or {}
            found[#found + 1] = entry
        end
    end
    return found
end

--- Every `path:line - words` hit over `paths`, reading each one through `read(path)`.
---
--- The reader is injected so the self-tests drive THIS function — the one the gate runs —
--- over fixture bodies held in memory, rather than a second copy of the walk that could agree with
--- itself while the real one drifted.
local function collect(paths, read, waived)
    local hits = {}
    for _, path in ipairs(paths) do
        local body = read(path)
        local pass = waived[path]
        local n = 0
        for line in (body:gsub("\r\n", "\n") .. "\n"):gmatch("([^\n]*)\n") do
            n = n + 1
            local found = britishIn(line)
            -- Per WORD, so every other British spelling in a waived file still reddens.
            if found and pass then
                local kept = {}
                for _, entry in ipairs(found) do
                    if not pass[entry] then kept[#kept + 1] = entry end
                end
                found = #kept > 0 and kept or nil
            end
            if found then
                hits[#hits + 1] = string.format("%s:%d - %s", path, n, table.concat(found, ", "))
            end
        end
    end
    return hits
end

-- ---------------------------------------------------------------------------
-- The gate
-- ---------------------------------------------------------------------------
local REGISTERED -- whether the carve-out's three cases armed at load; assigned below the gate

test("prose: no authored file carries a British spelling from localization-§5's published list",
function()
    local rules = consumerRules()
    local opts = options()
    if not REGISTERED and #allNarrowings(rules, opts.exempt) > 0 then
        fail("prose gate: a narrowing was declared after this suite loaded, so its refusals and"
            .. " disclosure never registered; set Kit.prose and the waiver file before Kit.run", 2)
    end

    local hits = collect(scannedPaths(rules, opts.exempt), function(path)
        local fh = io.open(path, "r")
        if not fh then
            fail("prose gate: git tracks " .. path .. " but it cannot be opened", 3)
        end
        local body = fh:read("*a") or ""
        fh:close()
        return body
    end, validateWaived(rules.waived))

    if #hits > 0 then
        -- Name every one rather than the first: these arrive a whole commit at a time, and
        -- clearing them a red run at a time is the slowest way to learn how many there were.
        fail(#hits .. " line(s) of authored text carry a British spelling (localization-§5). US "
            .. "English is the source dialect: WoW's own API is US-spelled, so a British-spelled "
            .. "identifier sits one letter from the Blizzard symbol beside it and a `grep -r color` "
            .. "silently misses half its call sites. Correct each, and if the spelling is a locale "
            .. "KEY move every locales/*.lua file and every call site in the same change. If it is "
            .. "game data or a library's field name, waive it in tests/prose_waivers.lua's `waived` "
            .. "table, per file AND per word, with the reason beside it. If EVERY hit in a file is "
            .. "there because a script generated the file, nothing loads it and .pkgmeta keeps it "
            .. "out of the packaged zip, name it in `Kit.prose.exempt` in tests/run.lua instead -- "
            .. "all three conditions, and a generated file that SHIPS is not exempt. NOT a way out "
            .. "is skipDirs or skipFiles: those face the same two refusals, over what they "
            .. "suppress as well as how they are written:\n          "
            .. table.concat(hits, "\n          "), 2)
    end
end)

test("prose: the gate carries localization-§5's two lists whole, and nothing of its own", function()
    if #BRITISH ~= PUBLISHED_BRITISH or #ALLOWED ~= PUBLISHED_ALLOWED then
        fail(string.format("the copied lists are %d BRITISH and %d ALLOWED entries; "
            .. "localization-§5 publishes %d and %d. A gate carrying a subset is the second "
            .. "anti-pattern stacked on the first (#46, testing-§12): it reads as coverage and "
            .. "provides none. Re-copy both blocks whole",
            #BRITISH, #ALLOWED, PUBLISHED_BRITISH, PUBLISHED_ALLOWED), 2)
    end

    -- The section's prose says an allowance is a correct US word that CONTAINS a British substring,
    -- and two of the published thirty-three do not: `syntheses` and `emphases` are the plurals of
    -- `synthesis` and `emphasis`, and neither plural contains its own entry. So that containment
    -- rule is described here rather than asserted. A gate that reddens on the list it is required to
    -- copy whole gets deleted rather than obeyed, and the divergence is the standard's to settle.

    -- Lowercase, because the scan lowercases the line and compares literally. An upper-case entry
    -- would never match anything and would sit in the list looking like coverage.
    local shouty = {}
    for _, entry in ipairs(BRITISH) do
        if entry ~= entry:lower() then shouty[#shouty + 1] = entry end
    end
    if #shouty > 0 then
        fail("BRITISH entries that are not lowercase, and therefore match nothing: "
            .. table.concat(shouty, ", "), 2)
    end
end)

-- ---------------------------------------------------------------------------
-- The carve-out's own three cases, registered only where a carve-out exists
-- ---------------------------------------------------------------------------
--
-- Nothing below registers in a repository that declared no narrowing of its own -- no
-- `Kit.prose.exempt` in the runner and no `skipDirs` or `skipFiles` in the waiver file. There is
-- nothing to disclose and nothing to refuse there, and three standing skips saying so every run
-- would be noise a reader learns to scroll past. The logic is proved everywhere all the same, by
-- the fixture-driven self-tests in `prose_selftests.lua`. BOTH CHANNELS ARM THESE CASES: keyed on
-- `Kit.prose.exempt` alone, the one repository that narrows the gate through the waiver file and
-- not the runner registered none of the three.
--
-- Read at load: the disclosure case's NAME carries its figures, fixed at registration. A narrowing
-- arriving later (a later suite writing `Kit.prose`) finds none armed, so the gate refuses it.

-- Whether to register at all -- and ONLY that. Everything below re-reads the live tables, because
-- the gate above reads them live too and a disclosure describing a different set from the one the
-- gate applied would be worse than none. A LIST THAT CANNOT BE READ REGISTERS RATHER THAN
-- VANISHING: a waiver file that does not load, or a `Kit.prose` that is not a table, would
-- otherwise take the count to nothing and silently retire the three cases with it.
REGISTERED = (function()
    local ok, count = pcall(function() return #allNarrowings(consumerRules(), declared()) end)
    return (not ok) or count > 0
end)()

--- The narrowing's reach: the resolved coverage set, how many tracked authored files it suppressed
--- between them, and how many this gate would otherwise have read. Measured through `filterPaths`
--- twice -- once with everything this repository declared, once with localization-§5's published
--- exclusions alone -- so the figures are the gate's own arithmetic and the paths named are
--- resolved against the same `all` that arithmetic counts.
local function narrowingReach()
    local rules, entries = consumerRules(), declared()
    local tracked = trackedPaths()
    local kitFiles, kitDirs = kitExclusionSets()
    local skipFiles, skipDirs = exclusionSets(rules)
    local all = filterPaths(tracked, kitFiles, kitDirs, {})
    local kept = filterPaths(tracked, skipFiles, skipDirs, resolveExempt(entries, tracked))
    return coverageOf(allNarrowings(rules, entries), all), #all - #kept, #all
end

--- The one resolved coverage set, read live, which both refusals below run over.
local function liveCoverage() return (narrowingReach()) end

--- The disclosure, as one line, or nil if the repository could not be read while loading.
local function reachLine()
    local ok, coverage, suppressed, total = pcall(narrowingReach)
    if not ok then return nil end
    return suppressed .. " of " .. total .. " tracked authored file(s), by: "
        .. coverageSummary(coverage)
end

if REGISTERED then

    -- Registered under the reading taken at load. A run that cannot reach git says so instead of
    -- claiming a figure, and the gate above fails on the same blindness a moment later.
    local DISCLOSED = reachLine()

    test("prose: the exclusions this repository declared suppressed "
        .. (DISCLOSED or "an unreadable number of files"), function()
        local now = reachLine()
        if now == nil then narrowingReach() end  -- re-raise the real reason, not an equality miss
        Kit.assertEqual(now, DISCLOSED,
            "the PASS line above is this run's disclosure of how far this repository narrowed the "
            .. "prose gate, by which entries and over which files, and a reader of a green suite "
            .. "has nothing else to go on. It is written into the case name when the suite loads "
            .. "and measured again here, so a runner or a waiver file that changes between the two "
            .. "reddens rather than printing a narrowing that is not the one applied")
    end)

    test("prose: no path this repository narrows the gate by is loaded by a TOC", function()
        local loaded, tocs = tocLoadedPaths()
        if tocs == 0 then
            Kit.skip("this repository tracks no .toc, so it packages no addon the client loads and "
                .. "localization-§5's LOADED BY NOTHING condition has no TOC to be read off. A "
                .. "library repository or a documentation repository is the normal case. What is "
                .. "left of the condition -- a dofile, a runtime reader -- is the auditor's, "
                .. "exactly as GENERATED RATHER THAN AUTHORED always is")
        end

        local bad = narrowingsLoadedByToc(liveCoverage(), loaded)
        if #bad > 0 then
            fail(#bad .. " path(s) this repository narrows the prose gate by are loaded by its own "
                .. "TOC: " .. table.concat(bad, "; ") .. ". No list may take a file the client "
                .. "loads out of this scan: localization-§5's carve-out is for generated data "
                .. "LOADED BY NOTHING, and its named exclusions are for text that is not this "
                .. "repository's English at all. A file the TOC loads is inside the packaged "
                .. "payload, so its spellings reach a player's screen, which is the one thing this "
                .. "rule exists to prevent -- in whichever list it is written, this is the "
                .. "whole-file waiver localization-§5 forbids. Correct the spelling, or waive it in "
                .. "tests/prose_waivers.lua's `waived` table, per file AND per word, with the "
                .. "reason beside it: the one narrowing these refusals do not police, because it "
                .. "cannot hide a spelling it did not name", 2)
        end
    end)

    test("prose: every path this repository narrows the gate by is one .pkgmeta keeps out of the zip",
    function()
        local body = readFile(".pkgmeta")
        if body == nil then
            local _, tocs = tocLoadedPaths()
            if tocs == 0 then
                Kit.skip("this repository has no .pkgmeta and tracks no .toc, so nothing in it is "
                    .. "packaged for a player to download and localization-§5's EXCLUDED FROM WHAT "
                    .. "A PLAYER DOWNLOADS condition has no packaging manifest to be read off. A "
                    .. "library repository or a documentation repository is the normal case")
            end
            fail("this repository packages an addon -- it tracks a .toc -- and has no .pkgmeta at "
                .. "its root, so the packager ships the working tree whole and every path this "
                .. "repository narrows the prose gate by is inside what a player downloads. "
                .. "localization-§5 excludes a file from this gate only when its spellings cannot "
                .. "reach a player; write the .pkgmeta ignore entries that keep them out, or stop "
                .. "narrowing the gate by them", 2)
        end

        local bad, unmatched = narrowingsNotIgnored(liveCoverage(), pkgmetaIgnores(body))
        if #bad > 0 then
            fail(#bad .. " path(s) this repository narrows the prose gate by are not ones .pkgmeta "
                .. "keeps out of the zip, so the packager puts them in what a player downloads: "
                .. table.concat(bad, ", ") .. ". Each is refused as written, or for a packaged "
                .. "file it covers without naming -- a narrowing is what it SUPPRESSES, and a "
                .. "prefix reaches past the folder .pkgmeta blessed. All three lists stand on the "
                .. "same condition: localization-§5 excludes a file only when its spellings cannot "
                .. "reach a player's screen, and a generated file that SHIPS is not exempt. Add "
                .. "the ignore entry, narrow the entry until it covers only what the packager "
                .. "drops, correct the spelling, or waive it in tests/prose_waivers.lua's "
                .. "`waived` table, per file AND per word, with the reason beside it", 2)
        end

        if #unmatched > 0 then
            fail(#unmatched .. " path(s) this repository narrows the prose gate by match nothing "
                .. "this gate would otherwise read: " .. table.concat(unmatched, ", ") .. ". The "
                .. "problem is the spelling rather than the packaging, which is why this says so "
                .. "instead of sending you to .pkgmeta: git writes forward slashes, no leading "
                .. "`./`, no trailing `/`, and is case-sensitive. A narrowing that suppresses "
                .. "nothing still reads as coverage of something: correct it, or delete it", 2)
        end
    end)

end

-- ---------------------------------------------------------------------------
-- The self-tests, in `prose_selftests.lua` beside this file
-- ---------------------------------------------------------------------------
--
-- Pure, fixture-driven, and still this suite's cases: kit revision 29 moved them unchanged to a file
-- the suite inventory does not read as a suite, and they register here, in the order they always
-- had. They drive the machinery above and these four functions of the scan's.
assert(loadfile(listsDir() .. "prose_selftests.lua"))(Kit, COVERAGE, {
    filterPaths = filterPaths, collect = collect,
    exclusionSets = exclusionSets, validateWaived = validateWaived,
})
