-- testkit/test_prose.lua — the US-English prose gate (localization-§5), over every file git tracks.
--
-- WHAT IT PROVES. That no authored file this repository tracks carries a British spelling from
-- localization-§5's published `BRITISH` list, once the `ALLOWED` US words that contain one of those
-- substrings have been taken out as whole words. Source, locale files, the TOC, `README.md` and
-- every document under `docs/` — the whole authored set, read from git.
--
-- IT SHIPS IN THE KIT, so a consumer inherits it instead of writing its own. Seven repositories had
-- written this gate by hand before it was, under three different file names, and four more had
-- none: a rule enforced by eleven hand-written copies is eleven chances to carry a subset. A
-- REPOSITORY WITH ITS OWN COPY WIRES ONE OR THE OTHER, NEVER BOTH.
--
-- It takes the kit as its chunk argument rather than reading the exposed table, for the reason
-- `test_eol.lua` does: that table's global name belongs to the consumer (`LK_TEST`, `AT_TEST`,
-- …) and a vendored suite cannot know which one it is standing in. Wire it as
-- `{ name = "test_prose", dir = "tests/_kit/" }` in the runner's suite list; the suite inventory
-- goes red until you do, so it cannot arrive with a re-vendor and then quietly run nothing.
--
-- BOTH LISTS ARE COPIED WHOLE, AND NOTHING IS ADDED. localization-§5 is explicit that a gate MUST
-- carry every `BRITISH` and `ALLOWED` entry and MUST NOT carry one the section does not publish: a
-- private list is a coverage claim no reader outside the repo can check. A British form the
-- published list misses is amended in the standard first and arrives here on the next sync.
--
-- THE GENERATED-DATA CARVE-OUT, AND WHY IT ARRIVES THROUGH THE OPTS TABLE. `layout-§1` settled this
-- exact question one revision earlier for the 1500-line cap, and the reasoning transfers whole. A
-- generated dump of the client's own strings is not this repository's English: it is Blizzard's,
-- regenerated by a script, and localization-§5 names it as the third shape a spelling may
-- legitimately carry here. It stands on three conditions, all ABOUT THE REPOSITORY —
--
--   * GENERATED rather than authored: a script writes it and a person does not edit it;
--   * LOADED BY NOTHING: no TOC line, no `dofile`, no runtime reader;
--   * EXCLUDED FROM WHAT A PLAYER DOWNLOADS: `.pkgmeta` keeps it out of the packaged zip.
--
-- — and no path betrays any of the three, so the exempt set ARRIVES THROUGH THE OPTS TABLE the way
-- `Kit.layoutCap.exempt` does, and nothing about a particular repository is compiled in here: a
-- reader who knows one gate knows both.
--
-- TWO OF THE THREE ARE GATED, AND THE FIRST DRAFT GATED NONE OF THEM. A path betrays nothing, but
-- the repository ROOT this gate runs in answers two of them out loud, and reading them is the
-- difference between a carve-out and the whole-file waiver localization-§5 forbids. Measured:
--
--   Kit.prose = { exempt = { "core/WhatGroup.lua", "docs/data-flow.md", "tests/" } }
--
-- WhatGroup's prose gate went GREEN, and `core\WhatGroup.lua` is line 48 of its TOC — five hits
-- suppressed, two of them inside the packaged payload, and the run printed not one word about it.
-- A carve-out that can swallow a shipped file is the escape the rule exists to close. So:
--
--   * A PATH THE TOC LOADS IS REFUSED. Every tracked `.toc` is parsed, its lines resolved against
--     its own folder and its backslashes read as the separators they are, and a declared narrowing
--     covering any of them reddens the run. It reads each TOC's OWN lines and nothing further: an
--     `.xml` line pulls in a tree of `.lua` the TOC never names, and a `dofile` inside a loaded
--     file pulls in more, so the rest of LOADED BY NOTHING stays with the auditor.
--
--   * A PATH `.pkgmeta` DOES NOT IGNORE IS REFUSED. The root `.pkgmeta`'s `ignore:` block is read,
--     and a narrowing no ignore entry covers reddens the run: if the packager puts it in the zip a
--     player downloads its spellings, which is the one thing this rule exists to prevent.
--
--   * WHERE THERE IS NO `.toc`, THE FIRST CHECK DEGRADES RATHER THAN DISAPPEARING: it SKIPS with
--     the reason printed rather than passing quietly, because a library or documentation repo has
--     no TOC for LOADED BY NOTHING to be read off, and a gate that goes green when it cannot look
--     is the failure this file is built against. Same for `.pkgmeta` where nothing is packaged;
--     but a `.toc` with NO `.pkgmeta` is refused, because the packager then ships the tree whole.
--
-- AND BOTH REFUSALS REACH BOTH CHANNELS, WHICH THE FIRST TWO DRAFTS DID NOT. There are two ways a
-- repository narrows this gate, and gating one of them is gating neither. `Kit.prose.exempt` in the
-- runner is the carve-out above; `skipDirs` and `skipFiles` in `tests/prose_waivers.lua` are the
-- named-exclusion list further down this file. They merge into the SAME exclusion sets and take
-- files out of the SAME scan, and until this revision they were checked against nothing at all --
-- while the refusal above pointed a consumer it had just refused straight at them. So every entry
-- in all three lists is a DECLARED NARROWING and both refusals run over the lot: what differs is
-- only what an entry MEANS to a reader, and no meaning survives the file being one that ships.
--
-- EACH CHANNEL IS REFUSED ON ITS OWN MATCHING RULE, never a shared one, AND BOTH REFUSALS READ ONE
-- RESOLVED COVERAGE SET. A `Kit.prose.exempt` entry covers a path or a folder, a `skipDirs` entry
-- is the plain prefix the scan compares, a `skipFiles` entry is one exact path -- matched more
-- loosely, a refusal would reject a narrowing that suppresses nothing; more tightly, it would wave
-- one through on the very file it does take out of the scan. Each entry is resolved through its OWN
-- rule ONCE and everything reads that one resolution, because resolving it apiece is how the two
-- refusals CAME TO DISAGREE ABOUT WHAT THEY REFUSED: packaging asked `.pkgmeta` about the entry AS
-- WRITTEN while the TOC asked about the paths it suppresses, and for an unanchored `skipDirs`
-- prefix checked against an `entry .. "/"` anchor those are different questions. Under a `.pkgmeta`
-- that ignores the `tools` folder, `skipDirs = { "tools" }` hid the shipped root file
-- `tools-notes.md` beside it with BOTH REFUSALS GREEN. Packaging therefore asks about the entry as
-- written AND about every path it covers: the first arm keeps a stale entry honest, the second
-- closes what it left open. An entry covering nothing is refused for its SPELLING instead, because
-- the packaging line would contradict the same run's disclosure.
--
-- THE KIT'S OWN EXCLUSIONS ARE NEITHER REFUSED NOR DISCLOSED. `libs/`, `tests/_kit/`,
-- `locales/enGB.lua` and the frozen dated bundles are localization-§5's published list, identical in
-- every repository and written down below; `libs/` is loaded by every TOC in the collection on
-- purpose. They are the baseline the disclosure measures FROM, not something this repository chose.
--
-- AND THE NARROWING IS DISCLOSED, IN ONE LINE COVERING BOTH CHANNELS. A passing case NAMES every
-- path this repository narrowed the gate by, says which of the three lists each came from, counts
-- the tracked authored files the lot of them suppressed AND NAMES THOSE FILES, grouped under the
-- entry that suppressed each. The count alone was what let a `.pkgmeta`-blessed entry over a
-- shipped file read as ratified rather than as suspicious: nothing tied the number to a file. The
-- list is BOUNDED and says so, because one entry can suppress hundreds and a truncated list a
-- reader takes for a complete one is worse than a count alone. The first draft printed nothing; the
-- second printed the carve-out alone, which is how the older and wider channel beside it went a
-- whole revision unexamined. That case and the two refusals register only where this repository
-- declared a narrowing of its own: an addon with no carve-out and no waiver file has nothing to
-- disclose, and three standing skips every run would be noise a reader learns to scroll past.
--
-- IT IS MEASURED, NOT HYPOTHETICAL. Without the carve-out this gate fails the one repository that
-- had already done everything the rule asked: PrettyChat tracks 27 generated `GlobalStrings/`
-- files, one of them 23,842 lines, and all 34 British spellings this gate reports there are
-- Blizzard constants or sentences. Its hand-written copy named the folder in its skip list and was
-- green; retiring it for this one, which testing-§9 requires, is what takes it red.
--
-- WHAT IT MUST NOT BECOME. localization-§5 forbids a whole-file waiver as a general escape — it
-- hides every OTHER British spelling in a file the repository edits often — and this carve-out
-- MUST NOT be one by the back door. An authored file somebody would rather not fix belongs in
-- `tests/prose_waivers.lua`'s `waived` table, per file AND per word, with the reason beside it:
-- the ONE narrowing the two refusals do not reach, because a waiver that has to name the word
-- cannot hide a spelling it did not name. Its SHAPE is still checked, in `validateWaived` below.
-- In particular: A GENERATED FILE THAT SHIPS IS NOT EXEMPT.
--
-- AND IT IS STILL NOT THE WAIVER FILE'S `skipDirs`, THOUGH THE TWO ARE NOW POLICED ALIKE. Those
-- answer localization-§5's own named-exclusion list — a frozen dated store this kit cannot know the
-- name of, a document whose subject is this rule — while the exempt set sits in `tests/run.lua`,
-- where an auditor already reads `Kit.layoutCap.exempt` naming the SAME folder for the SAME three
-- reasons. One consequence, stated rather than discovered in a red run: a British locale file
-- cannot be taken out by `skipFiles`, because it is TOC-loaded and shipped, so both refusals
-- reject it. `locales/enGB.lua` is excluded by name in the published list below.
--
-- THE THIRD CONDITION IS THE AUDITOR'S CALL AND NEVER THIS GATE'S, drawn where the cap gate draws
-- its equivalent. GENERATED RATHER THAN AUTHORED is a fact about how a file came to exist, and
-- nothing in the repository root records it, so the gate does not guess. A repository that puts a
-- hand-written file in the exempt set, past a TOC that does not load it and a `.pkgmeta` that
-- ignores it, has fooled the gate and will be caught by a reader — which is why the disclosure
-- exists: it puts that set, and the files it suppressed, in front of that reader every run.
--
-- WIRING, in the consumer's `tests/run.lua`, before `Kit.run`:
--
--   Kit.prose = { exempt = { "GlobalStrings/" } }   -- generated, loaded by nothing, not packaged
--
-- Optional, and absent is the normal case: ten of the eleven addons that vendor this kit have no
-- generated data. An entry is a tracked path, or a folder ending in `/`. The waiver file's
-- `skipDirs` and `skipFiles` are the other two lists a repository can narrow this gate by, and
-- every word above about the refusals and the disclosure applies to them unchanged.
--
-- IT FAILS RATHER THAN PASSES WHEN IT CANNOT LOOK. No `io.popen`, no git, an unreadable tracked file
-- — every one of those is a failure, not a skip. A gate that goes quiet when it is blind reports
-- success, which is worse than not existing. Same bargain `test_eol.lua` strikes.

local Kit = ...
local test, fail = Kit.test, Kit.fail

-- ---------------------------------------------------------------------------
-- The published lists (localization-§5), copied whole, and the folder exclusions
-- ---------------------------------------------------------------------------

-- In `prose_lists.lua` beside this file since kit revision 26, so that the lists can grow without
-- taking this gate past `layout-§1`'s cap. Found from this chunk's own name, the way `mock_base.lua`
-- finds `mock_record.lua`, with the vendored layout as the fallback. A missing file raises at load:
-- a gate with no list to read would pass every file it scans.
local function listsDir()
    local info = debug and debug.getinfo and debug.getinfo(1, "S")
    local dir = info and tostring(info.source or ""):match("^@(.*[/\\])")
    local f = dir and io.open(dir .. "prose_lists.lua", "r")
    if f then f:close(); return dir end
    return "tests/_kit/"
end

local LISTS = dofile(listsDir() .. "prose_lists.lua")
local BRITISH, ALLOWED = LISTS.BRITISH, LISTS.ALLOWED
local PUBLISHED_BRITISH, PUBLISHED_ALLOWED = LISTS.PUBLISHED_BRITISH, LISTS.PUBLISHED_ALLOWED
local SKIPPED_DIRS = LISTS.SKIPPED_DIRS

-- The store-root files read although a kit folder above covers them (`SCAN_BACK`, revision 26), and
-- the kit folders they are read back from. Sets, because `filterPaths` asks both per path.
local SCAN_BACK, KIT_DIRS = {}, {}
for _, path in ipairs(LISTS.SCAN_BACK) do SCAN_BACK[path] = true end
for _, dir in ipairs(SKIPPED_DIRS) do KIT_DIRS[dir] = true end

-- ---------------------------------------------------------------------------
-- What is scanned, and what is not
-- ---------------------------------------------------------------------------

-- The exclusions localization-§5 names, and only those. The folders are `SKIPPED_DIRS`, in
-- `prose_lists.lua` with the spellings, which also names in `SCAN_BACK` the three store-root files
-- read back out of them; the files are below. Every one is a directory or a file
-- rather than a pattern, so the list cannot quietly grow by widening a regex: `locales/enGB.lua`,
-- which is what a British locale file is for, and the gate itself, which quotes every forbidden
-- spelling in order to forbid it.
local SKIPPED_FILES = {
    ["locales/enGB.lua"] = true,
    ["tests/test_prose.lua"] = true,
    ["tests/test_spelling.lua"] = true,
    -- The waiver file is the fourth exclusion, for the same reason the gate is: every reason
    -- written beside a waiver is prose ABOUT a forbidden spelling, and a gate that scans it
    -- reddens on the file whose whole job is to record what it must not correct.
    ["tests/prose_waivers.lua"] = true,
}

-- ---------------------------------------------------------------------------
-- The consumer facts: localization-§5's generated-data carve-out
-- ---------------------------------------------------------------------------

--- The opts table the runner sets on the kit, or an empty one.
---
--- A missing table is not a failure: an absent `exempt` means a repository with no generated data,
--- which is ten of the eleven. It rides on the kit table for the reason the suite takes the kit as
--- its chunk argument at all — the exposed table's global name belongs to the consumer (`LK_TEST`,
--- `AT_TEST`, …) and a vendored suite cannot know which one it is standing in.
---
--- The validator is split out from the reader BECAUSE OF A DEFECT THIS FILE SHIPPED: the self-test
--- for the absent case saved `Kit.prose`, set a bad value, RESTORED IT, and only then read it back,
--- so the assertion landed on the LIVE RUNNER's carve-out -- permanently green where none is
--- declared, permanently red in the one repository it exists for. In a pure function the self-tests
--- drive it over fixtures and no case here touches `Kit.prose`.
local function validateOptions(o)
    if o == nil then return {} end
    if type(o) ~= "table" then
        fail("prose gate: Kit.prose is the consumer-facts table -- { exempt = { ... } } -- and this "
            .. "runner set it to a " .. type(o), 3)
    end
    return o
end

local function options() return validateOptions(Kit.prose) end

--- The live carve-out, read the same way and at the same moment the gate reads it.
local function declared() return options().exempt end

--- True when the opts entry `entry` covers `path`: the path itself, or a folder containing it.
---
--- Globs are not expanded: an entry that would only match through one matches nothing, which errs
--- toward reporting a spelling rather than excusing a file nobody meant to excuse. The folder form
--- compares against `entry .. "/"`, so a sibling whose name merely STARTS with it —
--- `GlobalStringsNotes.md` beside `GlobalStrings/` — is not swept in by a prefix match.
local function exemptEntryCovers(entry, path)
    if entry == path then return true end
    local folder = (entry:sub(-1) == "/") and entry or (entry .. "/")
    return path:sub(1, #folder) == folder
end

--- The opts-borne exempt set, resolved against the tracked paths into a set of concrete paths.
---
--- Takes an array of paths and folders, a map of path to true, or both — a runner writes whichever
--- reads better beside the reason it is passing them, exactly as `Kit.layoutCap.exempt` does. An
--- entry matching nothing resolves to an empty set here; what becomes of it is the refusals' call.
-- The three lists a repository can narrow this gate by, spelled the way a message must name them.
-- A reader told only WHICH path was refused still has to guess which file to open, and two of the
-- three live in a different file from the third.
local SOURCE_EXEMPT    = "Kit.prose.exempt in tests/run.lua"
local SOURCE_SKIPDIRS  = "skipDirs in tests/prose_waivers.lua"
local SOURCE_SKIPFILES = "skipFiles in tests/prose_waivers.lua"
local SOURCE_WAIVED    = "waived in tests/prose_waivers.lua"

--- One list's entries as the repository wrote them, validated, in a stable order.
---
--- Shared by all three lists, so a malformed `skipDirs` is refused in the same words a malformed
--- `Kit.prose.exempt` is, and the scan and the refusals can never read one differently from the
--- other. `source` names the list in the message; it is the only thing that varies. Sorted, because
--- a set whose printed order depends on `pairs` is a line that changes when nothing did.
---
--- Array or map, either way. The map form's `false` value declares nothing and is dropped, which is
--- what it already meant to the scan.
local function declaredEntries(entries, source)
    source = source or SOURCE_EXEMPT
    local list = {}
    if entries == nil then return list end
    if type(entries) ~= "table" then
        fail("prose gate: " .. source .. " is a set of paths that narrow this gate, written as an "
            .. "array or as a map; this repository set it to a " .. type(entries), 3)
    end
    for key, value in pairs(entries) do
        local entry = (type(key) == "number") and value or (value and key)
        if entry ~= nil then
            if type(entry) ~= "string" then
                fail("prose gate: every entry in " .. source .. " is a tracked path or a folder "
                    .. "ending in `/`; this one is a " .. type(entry), 3)
            end
            list[#list + 1] = entry
        end
    end
    table.sort(list)
    return list
end

local function resolveExempt(entries, paths)
    local set = {}
    for _, entry in ipairs(declaredEntries(entries, SOURCE_EXEMPT)) do
        for _, path in ipairs(paths) do
            if exemptEntryCovers(entry, path) then set[path] = true end
        end
    end
    return set
end

-- ---------------------------------------------------------------------------
-- A declared narrowing, whichever of the three lists it was written in
-- ---------------------------------------------------------------------------

--- One entry a repository narrowed this gate by: the text it wrote, the list it wrote it in, and
--- the predicate saying which tracked paths that entry takes out of the scan.
---
--- `covers` is the CHANNEL'S OWN matching rule rather than a shared approximation, because the
--- refusals must refuse exactly what the scan suppresses: `exemptEntryCovers` for the carve-out,
--- `dirCovers`, the prefix-with-scan-back `filterPaths` asks for `skipDirs`, one exact key for
--- `skipFiles`.
local function narrowing(entry, source, covers)
    return { entry = entry, source = source, covers = covers }
end

--- The runner's carve-out, as narrowings.
local function exemptNarrowings(entries)
    local out = {}
    for _, entry in ipairs(declaredEntries(entries, SOURCE_EXEMPT)) do
        out[#out + 1] = narrowing(entry, SOURCE_EXEMPT,
            function(path) return exemptEntryCovers(entry, path) end)
    end
    return out
end

--- Whether a `skipDirs` entry, kit or repository, takes `path` out of the scan: the unanchored
--- prefix, except that a `SCAN_BACK` file is kept against a kit folder, and against a repository
--- entry that only restates one. `filterPaths` and the refusals both ask this, so a restated kit
--- folder cannot be disclosed or refused as covering the store-root file the scan reads.
local function dirCovers(dir, path)
    return path:sub(1, #dir) == dir and not (SCAN_BACK[path] and KIT_DIRS[dir])
end

--- The waiver file's two exclusion lists, as narrowings.
---
--- THE OLDER AND WIDER CHANNEL, and the one that went two revisions with no check on it at all: it
--- reaches the same exclusion sets, so it faces the same refusals and the same disclosure.
local function waiverNarrowings(rules)
    local out = {}
    for _, dir in ipairs(declaredEntries(rules.skipDirs, SOURCE_SKIPDIRS)) do
        out[#out + 1] = narrowing(dir, SOURCE_SKIPDIRS,
            function(path) return dirCovers(dir, path) end)
    end
    for _, file in ipairs(declaredEntries(rules.skipFiles, SOURCE_SKIPFILES)) do
        out[#out + 1] = narrowing(file, SOURCE_SKIPFILES,
            function(path) return path == file end)
    end
    return out
end

--- Every narrowing this repository declared, from all three lists, in one stable order.
local function allNarrowings(rules, exemptEntries)
    local out = exemptNarrowings(exemptEntries)
    for _, n in ipairs(waiverNarrowings(rules or {})) do out[#out + 1] = n end
    table.sort(out, function(a, b)
        if a.entry ~= b.entry then return a.entry < b.entry end
        return a.source < b.source
    end)
    return out
end

-- ---------------------------------------------------------------------------
-- The two carve-out conditions the repository root answers out loud
-- ---------------------------------------------------------------------------
--
-- Pure, every one of them: text in, findings out. They are driven by the cases below over the two
-- real repositories' own `.toc` and `.pkgmeta` bodies held as fixtures, so the logic is proved in
-- every repository that vendors this kit rather than only in the one that happens to declare a
-- carve-out. This library repo declares none and has no `.toc` at all, so nothing else would.

--- A path as a TOC or a `.pkgmeta` spells it, rewritten the way git spells it: forward slashes, no
--- leading `./`, no trailing `/`. A TOC uses the client's backslashes; the two must be comparable.
local function normalizePath(path)
    path = path:gsub("\\", "/"):gsub("^%./", "")
    while path:sub(-1) == "/" do path = path:sub(1, -2) end
    return path
end

--- Every path a TOC body loads, as `{ path =, line =, toc = }`, resolved against the TOC's folder.
---
--- A TOC is line-oriented: `##` is a directive, `#` a comment, a blank line is nothing, and every
--- other line is a file the client loads. Paths are relative to the folder the TOC sits in, so a
--- vendored library's TOC names ITS files and not this repository's — which is why the folder is
--- prefixed rather than the line taken as a repository path.
local function tocLoads(tocPath, body)
    local dir = tocPath:match("^(.*/)") or ""
    local out, n = {}, 0
    for line in (body:gsub("\r\n", "\n") .. "\n"):gmatch("([^\n]*)\n") do
        n = n + 1
        local entry = line:match("^%s*(.-)%s*$")
        if entry ~= "" and entry:sub(1, 1) ~= "#" then
            out[#out + 1] = { path = dir .. normalizePath(entry), line = n, toc = tocPath }
        end
    end
    return out
end

--- The `ignore:` block of a `.pkgmeta` body, as an array of entries.
---
--- `.pkgmeta` is YAML the BigWigs packager reads and `ignore:` is a block sequence of paths
--- relative to the repository root. ONLY that key is read: a sibling key at column zero closes the
--- block, so `externals:` or `move-folders:` below can never be mistaken for ignores, while an
--- indented comment or a blank line leaves it open -- both ordinary in this collection's files.
local function pkgmetaIgnores(body)
    local out, inside = {}, false
    for line in (body:gsub("\r\n", "\n") .. "\n"):gmatch("([^\n]*)\n") do
        local stripped = line:gsub("%s+$", "")
        if stripped:match("^ignore:%s*$") then
            inside = true
        elseif inside then
            local item = stripped:match("^%s+%-%s*(.+)$")
            if item then
                item = item:gsub("%s+#.*$", "")
                item = item:match('^"(.*)"$') or item:match("^'(.*)'$") or item
                out[#out + 1] = normalizePath(item)
            elseif stripped:match("^%S") then
                inside = false
            end
        end
    end
    return out
end

--- True when the `.pkgmeta` ignore entry `entry` keeps `path` out of the packaged zip.
---
--- Exact, a folder containing it, or the packager's `*` wildcard — matched against the whole path
--- and against the basename alone, because `- "*.bak"` means a backup anywhere and
--- `- media/logos/*.png` means one folder, and both spellings are in this collection today. A
--- non-match REFUSES, so the wildcard is read generously: too narrowly is a legitimate carve-out
--- a consumer cannot get past.
local function ignoreCovers(entry, path)
    entry, path = normalizePath(entry), normalizePath(path)
    if entry == "" then return false end
    if entry == path then return true end
    if path:sub(1, #entry + 1) == entry .. "/" then return true end
    if entry:find("*", 1, true) then
        local pattern = "^" .. entry:gsub("[%^%$%(%)%%%.%[%]%+%-%?]", "%%%0"):gsub("%*", ".-") .. "$"
        if path:find(pattern) then return true end
        if (path:match("([^/]+)$") or path):find(pattern) then return true end
    end
    return false
end

-- ── one resolved coverage set, and the two refusals that read it ──────────────

--- Every narrowing with the tracked paths it actually suppresses, resolved through its OWN
--- `covers` rule, in the order `allNarrowings` sorted them and with each path list sorted.
---
--- ONE RESOLUTION FOR BOTH REFUSALS AND THE DISCLOSURE, WHICH IS THE POINT OF THIS FUNCTION. They
--- computed coverage apiece -- the TOC refusal asked `covers` about the paths a TOC loads, the
--- packaging refusal asked `.pkgmeta` about the ENTRY AS WRITTEN -- and for an unanchored
--- `skipDirs` prefix those are different questions: coverage spilled past the boundary the refusal
--- checked, and a shipped root file sat behind an ignored folder of nearly the same name with both
--- refusals green. Two computations of one fact is how they disagreed; one is how they cannot.
--- `paths` is what this gate would read had the repository declared nothing -- tracked, authored,
--- minus localization-§5's published exclusions -- so a coverage list is exactly what the entry
--- takes out of THIS scan.
local function coverageOf(narrowings, paths)
    local out = {}
    for _, n in ipairs(narrowings) do
        local covered = {}
        for _, path in ipairs(paths) do
            if n.covers(path) then covered[#covered + 1] = path end
        end
        table.sort(covered)
        out[#out + 1] = { entry = n.entry, source = n.source, paths = covered }
    end
    return out
end

--- `entry [source]`: what every refusal and the disclosure name a narrowing by. The list it came
--- from travels with it -- a line naming a path alone leaves the reader hunting two files for it.
local function coverageLabel(c) return c.entry .. " [" .. c.source .. "]" end

--- At most `max` of `paths`, with the remainder COUNTED rather than dropped quietly, and the line
--- saying it was bounded so nobody reads a truncated list as a complete one.
local function boundedPaths(paths, max)
    local shown = {}
    for i = 1, math.min(max, #paths) do shown[i] = paths[i] end
    local text = table.concat(shown, ", ")
    if #paths > #shown then
        text = text .. ", and " .. (#paths - #shown) .. " more (list bounded)"
    end
    return text
end

--- The disclosure's `by:` clause: each entry, the list it came from, how many tracked authored
--- files it suppressed, and WHICH ones.
---
--- Naming them is the half that was missing: a count with nothing under it is what made a
--- `.pkgmeta`-blessed entry over a shipped file read as ratified. Past `COVERAGE_LIST_MAX` paths
--- every entry falls back to its count and `COVERAGE_EXAMPLES` of them, saying the list is bounded.
local COVERAGE_LIST_MAX = 12
local COVERAGE_EXAMPLES = 3

local function coverageSummary(coverage)
    local named = 0
    for _, c in ipairs(coverage) do named = named + #c.paths end
    local max = (named > COVERAGE_LIST_MAX) and COVERAGE_EXAMPLES or named
    local out = {}
    for _, c in ipairs(coverage) do
        out[#out + 1] = coverageLabel(c) .. " (" .. #c.paths .. ")"
            .. ((#c.paths == 0) and ": nothing" or (": " .. boundedPaths(c.paths, max)))
    end
    return table.concat(out, "; ")
end

--- The narrowings some TOC loads a file through, named with the list they came from and with the
--- TOC line that loads it, sorted.
---
--- Read off the resolved coverage rather than off `covers` a second time, so this refusal and the
--- packaging one below can never again refuse two different things. A path a TOC names but this
--- scan would never read -- an `.xml` include, an untracked file -- is suppressed by nothing.
local function narrowingsLoadedByToc(coverage, loaded)
    local bad = {}
    for _, c in ipairs(coverage) do
        local covered = {}
        for _, path in ipairs(c.paths) do covered[path] = true end
        for _, hit in ipairs(loaded) do
            if covered[hit.path] then
                bad[#bad + 1] = coverageLabel(c) .. " (loads " .. hit.path .. ", line "
                    .. hit.line .. " of " .. hit.toc .. ")"
                break
            end
        end
    end
    table.sort(bad)
    return bad
end

--- True when some `.pkgmeta` ignore entry keeps `path` out of the packaged zip.
local function ignoredByPkgmeta(ignores, path)
    for _, ignore in ipairs(ignores) do
        if ignoreCovers(ignore, path) then return true end
    end
    return false
end

--- Two findings out of the ONE coverage set: the narrowings `.pkgmeta` does not keep out of the
--- zip, and the narrowings that suppress nothing at all.
---
--- ASKED OF THE ENTRY AS WRITTEN AND OF EVERY PATH IT COVERS, because those are not one question.
--- The entry arm is deliberate strictness -- an entry covering nothing today still has to be one
--- the packager would drop if it covered something tomorrow -- and the coverage arm closes what
--- that arm left open: coverage spills past the boundary it checks, past a `.pkgmeta` that blessed
--- the entry and shipped the file.
---
--- AN ENTRY COVERING NOTHING IS REPORTED SEPARATELY, and only where the entry arm already refused
--- it: the problem there is the entry's SPELLING, and the same run's disclosure says it suppressed
--- nothing, so sending the reader to `.pkgmeta` prints two lines that contradict each other. It
--- stays red; a stale entry `.pkgmeta` DOES cover stays stale rather than silent and not a failure,
--- as `Kit.layoutCap.exempt` treats one.
local function narrowingsNotIgnored(coverage, ignores)
    local bad, unmatched = {}, {}
    for _, c in ipairs(coverage) do
        if not ignoredByPkgmeta(ignores, c.entry) then
            local into = (#c.paths == 0) and unmatched or bad
            into[#into + 1] = coverageLabel(c)
        else
            local shipped = {}
            for _, path in ipairs(c.paths) do
                if not ignoredByPkgmeta(ignores, path) then shipped[#shipped + 1] = path end
            end
            if #shipped > 0 then
                bad[#bad + 1] = coverageLabel(c) .. " (.pkgmeta ignores the entry, but it "
                    .. "suppresses " .. #shipped .. " packaged file(s) it does not name: "
                    .. boundedPaths(shipped, COVERAGE_EXAMPLES) .. ")"
            end
        end
    end
    table.sort(bad)
    table.sort(unmatched)
    return bad, unmatched
end

-- ---------------------------------------------------------------------------
-- What the consumer adds: its own exclusions and its waivers
-- ---------------------------------------------------------------------------

--- The optional `tests/prose_waivers.lua`, which a consumer writes and this file reads.
---
--- WHY THIS SEAM EXISTS AT ALL, rather than the kit carrying the exceptions. Some British spellings
--- in a Ka0s tree are not the repository's English to correct, and the kit cannot know which:
--- AceTimer's flag field carries the British double-L spelling of *canceled* and a handle records
--- the flag under that name, because that is what `tests/_kit/mock_record.lua`'s live-timer survey
--- reads off it -- correct it and a stand-down suite's timer assertion goes quietly unfalsifiable.
--- Blizzard spells its `LFG_LIST_APPLICATION_STATUS_UPDATED` status the same way, and an addon
--- matches it verbatim off the event. localization-§5 already says to match game data on the token
--- the game uses; this is that rule meeting this gate. A GENERATED DUMP OF THE CLIENT'S OWN STRINGS
--- IS NOT ONE OF THESE and does not belong here: it is `Kit.prose.exempt` in the runner, beside
--- `Kit.layoutCap.exempt` naming the same folder.
---
--- THE SHAPE IS PER FILE AND PER WORD, never per file alone. A whole-file waiver hides every other
--- British spelling in a file the repo edits often, which is how a gate acquires a blind spot the
--- size of a module. Returning:
---
---     return {
---       skipDirs = { "docs/spell-research/" },        -- optional, named not patterned
---       skipFiles = { ["docs/vendor-notes.md"] = true },
---       waived = {
---         ["core/LifecycleSetup.lua"] = { ["cancel" .. "led"] = true },
---       },
---     }
---
--- `skipDirs` AND `skipFiles` EXTEND THE NAMED EXCLUSION LIST ABOVE, and nothing wider. They are
--- for the categories localization-§5 already names but this kit cannot spell for a consumer — a
--- frozen dated store under a name only that repo knows, a document whose subject is this rule --
--- and not a home for generated data: that is the opts-borne carve-out, in the runner.
---
--- AND THEY FACE THE SAME TWO REFUSALS `Kit.prose.exempt` DOES, over the same resolved coverage: an
--- entry a TOC loads is refused, and one `.pkgmeta` does not ignore -- as written, or for a file it
--- covers -- is refused, because whatever a reader means by the entry, a file inside the packaged
--- payload carries its spellings to a player's screen. They appear in the same disclosure too.
--- `waived` is the only list here not policed that way: it names the word, so it cannot hide one it
--- did not name. Its SHAPE is validated all the same, in `validateWaived` below.
---
--- ABSENT IS THE NORMAL CASE and means no waivers. A repo with nothing to waive ships no file.
local function consumerRules()
    local chunk = loadfile("tests/prose_waivers.lua")
    if not chunk then return {} end
    local ok, rules = pcall(chunk)
    if not ok or type(rules) ~= "table" then
        fail("prose gate: tests/prose_waivers.lua exists but did not return a table (" ..
            tostring(rules) .. "). A waiver file that cannot be read must not be treated as "
            .. "an empty one, because that silently widens the gate", 2)
    end
    return rules
end

--- `waived`, validated. The third key in the same table, and until now the only one with no
--- validation at all: a `waived` that was not a table died inside the scan with a raw Lua error
--- instead of this gate's own words, and the ARRAY FORMS -- `waived = { "core/Foo.lua" }`, or a
--- file's words written as `{ "cancel" .. "led" }` -- waived NOTHING and said nothing, because the
--- scan looks both up by key. That is the silence just removed from `skipFiles`, one key over.
---
--- IT IS POLICED FOR SHAPE HERE AND BY NOTHING ELSE, deliberately: `waived` stays outside the two
--- refusals because it is per FILE and per WORD, so it cannot hide a spelling it did not name --
--- which is why both refusals point at it as the way out. What it CAN do is waive nothing while
--- looking like a waiver.
local function validateWaived(waived)
    if waived == nil then return {} end
    if type(waived) ~= "table" then
        fail("prose gate: " .. SOURCE_WAIVED .. " maps a tracked path to the words waived in it, "
            .. "per file AND per word; this repository set it to a " .. type(waived), 3)
    end
    for path, words in pairs(waived) do
        if type(path) ~= "string" then
            fail("prose gate: " .. SOURCE_WAIVED .. " is KEYED by the path being waived; this key "
                .. "is a " .. type(path) .. ", so the array form waives nothing rather than "
                .. "saying so", 3)
        elseif type(words) ~= "table" then
            fail("prose gate: " .. SOURCE_WAIVED .. "'s entry for " .. path .. " is the set of "
                .. "words waived in that file, per WORD and never per file alone; this one is a "
                .. type(words) .. ", and a whole-file waiver is what localization-§5 forbids", 3)
        else
            for word in pairs(words) do
                if type(word) ~= "string" then
                    fail("prose gate: " .. SOURCE_WAIVED .. "'s entry for " .. path .. " is keyed "
                        .. "by the British spelling being waived, lowercase, as localization-§5 "
                        .. "publishes it; this key is a " .. type(word) .. ", so that array form "
                        .. "waives nothing either", 3)
                end
            end
        end
    end
    return waived
end

--- True when `path` is authored text this section has an opinion about.
---
--- Extension rather than directory, because the authored set is not one tree: locale values sit in
--- `locales/`, comments in `core/`, prose in `docs/` and the TOC's own notes at the root.
--- `.luacheckrc` is named on its own — it is authored Lua with authored comments wearing a different
--- extension, and an extension rule alone would miss it.
local function isAuthoredText(path)
    return path:find("%.lua$") or path:find("%.md$") or path:find("%.toc$") or path == ".luacheckrc"
end

--- Split a NUL-delimited blob. `git ls-files -z` because a path may contain anything but NUL, and
--- the line-oriented form quotes such a path instead of printing it — a quoted path would not open,
--- and this gate would then report a read failure that is really a parse failure.
local function splitNul(blob)
    local out, start = {}, 1
    while true do
        local i = blob:find("\0", start, true)
        if not i then break end
        if i > start then out[#out + 1] = blob:sub(start, i - 1) end
        start = i + 1
    end
    return out
end

--- The authored paths among `all`, minus the named exclusions and minus the exempt set, in order.
---
--- Pure, and separated from the git call below so the self-tests can drive it over a fixture list.
--- The exempt set drops the file outright rather than filtering its hits: a carved-out dump is
--- generated data the gate has no opinion about, and PrettyChat's is 1.6 MB it would read to say
--- nothing.
---
--- A `SCAN_BACK` file is kept against a kit folder, and against a repository `skipDirs` entry that
--- only restates one (`dirCovers`); a wider `skipDirs` entry, or `skipFiles`, still drops it.
local function hiddenByDir(path, skipDirs)
    for _, dir in ipairs(skipDirs) do
        if dirCovers(dir, path) then return true end
    end
    return false
end

local function filterPaths(all, skipFiles, skipDirs, exempt)
    local paths = {}
    for _, path in ipairs(all) do
        if isAuthoredText(path) and not skipFiles[path] and not exempt[path]
            and not hiddenByDir(path, skipDirs) then
            paths[#paths + 1] = path
        end
    end
    return paths
end

--- Every path `git ls-files` reports, read once and kept for the rest of the run.
---
--- Memoized because four readers want it — the scan, the two refusals and the disclosure, which
--- wants it while the suite is still LOADING to write its own case name. A failed read is never
--- cached, so blindness is reported every time rather than once. It is asked of the WHOLE tracked
--- set, before any filtering: an empty answer AFTER filtering has two causes with opposite
--- meanings — git said nothing, or a runner exempted everything — so each is reported as itself,
--- here and at the end of `scannedPaths`.
local trackedCache
local function trackedPaths()
    if trackedCache then return trackedCache end
    if not io.popen then
        fail("prose gate: io.popen is unavailable, so the tracked set cannot be read and this gate "
            .. "must not be reported as passing", 3)
    end
    local pipe = io.popen("git ls-files -z")
    if not pipe then
        fail("prose gate: io.popen returned no handle for `git ls-files`, so this gate cannot run "
            .. "and must not be reported as passing", 3)
    end
    local blob = pipe:read("*a") or ""
    pipe:close()

    local tracked = splitNul(blob)
    if #tracked == 0 then
        fail("prose gate: `git ls-files` reported no tracked files at all, which cannot be true -- "
            .. "either git is unavailable or this is not a repository; this gate cannot run, and "
            .. "must not be reported as passing", 3)
    end
    trackedCache = tracked
    return tracked
end

--- The body of `path`, or nil when it cannot be opened.
local function readFile(path)
    local fh = io.open(path, "r")
    if not fh then return nil end
    local body = fh:read("*a") or ""
    fh:close()
    return body
end

--- localization-§5's own named exclusions, as the two shapes `filterPaths` takes, and nothing else.
---
--- The baseline the disclosure measures FROM: the same in every repository, and `libs/` is loaded
--- by every TOC on purpose, so they are neither refused nor disclosed. What a repository ADDS is.
local function kitExclusionSets()
    local skipFiles = {}
    for k, v in pairs(SKIPPED_FILES) do skipFiles[k] = v end
    local skipDirs = {}
    for _, d in ipairs(SKIPPED_DIRS) do skipDirs[#skipDirs + 1] = d end
    return skipFiles, skipDirs
end

--- The named exclusions plus the consumer's, as the two shapes `filterPaths` takes.
---
--- Built from `waiverNarrowings`, the same reader the two refusals and the disclosure use. ONE
--- READER IS THE POINT: a scan that read `skipFiles` one way while the refusals read it another is
--- a narrowing policed in a shape nobody wrote. It also fixed a silence -- the array form
--- `skipFiles = { "docs/notes.md" }` was copied across key and all, leaving a numeric key no path
--- lookup could hit, so a consumer who wrote it excluded nothing and was told nothing.
local function exclusionSets(rules)
    local skipFiles, skipDirs = kitExclusionSets()
    for _, n in ipairs(waiverNarrowings(rules)) do
        if n.source == SOURCE_SKIPFILES then
            skipFiles[n.entry] = true
        else
            skipDirs[#skipDirs + 1] = n.entry
        end
    end
    return skipFiles, skipDirs
end

--- Every path every tracked `.toc` loads, and how many TOCs were read.
---
--- Zero TOCs is not a failure and not a silence either: the caller SKIPS with the reason, because
--- a repository that packages no addon has no TOC for LOADED BY NOTHING to be read off. A TOC git
--- tracks and this process cannot open IS a failure -- the gate going blind on the condition.
local function tocLoadedPaths()
    local loaded, count = {}, 0
    for _, path in ipairs(trackedPaths()) do
        if path:find("%.toc$") then
            count = count + 1
            local body = readFile(path)
            if body == nil then
                fail("prose gate: git tracks " .. path .. " but it cannot be opened, and it is "
                    .. "where the carve-out's LOADED BY NOTHING condition is read; this gate "
                    .. "cannot look and must not be reported as passing", 3)
            end
            for _, hit in ipairs(tocLoads(path, body)) do loaded[#loaded + 1] = hit end
        end
    end
    return loaded, count
end

--- Every authored path git tracks, minus the named exclusions and the carve-out, in git's order.
local function scannedPaths(rules, exemptEntries)
    local tracked = trackedPaths()
    local skipFiles, skipDirs = exclusionSets(rules)

    local paths = filterPaths(tracked, skipFiles, skipDirs, resolveExempt(exemptEntries, tracked))
    if #paths == 0 then
        fail("prose gate: git tracks " .. #tracked .. " file(s) and the exclusions and the "
            .. "carve-out between them removed every authored one, so this gate would read "
            .. "nothing and report green. Narrow `Kit.prose.exempt` in tests/run.lua, or the "
            .. "skipDirs or skipFiles in tests/prose_waivers.lua, until it reads the repository "
            .. "again -- the disclosure case names which of the three every path came from", 2)
    end
    return paths
end

--- The British substrings present in one line, after `ALLOWED` has been taken out as whole words.
---
--- Whole words, and before the scan, exactly as localization-§5 requires: delimit on non-letters,
--- drop a token that IS an allowance, run the substrings over what is left. Matching `ALLOWED` as a
--- substring would swallow *analysed* inside the allowance for *analyses*.
local ALLOWED_SET = {}
for _, word in ipairs(ALLOWED) do ALLOWED_SET[word] = true end

local function britishIn(line)
    local lowered = line:lower()
    local kept = lowered:gsub("%a+", function(token)
        if ALLOWED_SET[token] then return "" end
        return token
    end)

    local found
    for _, entry in ipairs(BRITISH) do
        if kept:find(entry, 1, true) then
            found = found or {}
            found[#found + 1] = entry
        end
    end
    return found
end

--- Every `path:line - words` hit over `paths`, reading each one through `read(path)`.
---
--- The reader is injected so the self-tests below drive THIS function — the one the gate runs —
--- over fixture bodies held in memory, rather than a second copy of the walk that could agree with
--- itself while the real one drifted.
local function collect(paths, read, waived)
    local hits = {}
    for _, path in ipairs(paths) do
        local body = read(path)
        local pass = waived[path]
        local n = 0
        for line in (body:gsub("\r\n", "\n") .. "\n"):gmatch("([^\n]*)\n") do
            n = n + 1
            local found = britishIn(line)
            -- Per WORD, so every other British spelling in a waived file still reddens.
            if found and pass then
                local kept = {}
                for _, entry in ipairs(found) do
                    if not pass[entry] then kept[#kept + 1] = entry end
                end
                found = #kept > 0 and kept or nil
            end
            if found then
                hits[#hits + 1] = string.format("%s:%d - %s", path, n, table.concat(found, ", "))
            end
        end
    end
    return hits
end

-- ---------------------------------------------------------------------------
-- The gate
-- ---------------------------------------------------------------------------
local REGISTERED -- whether the carve-out's three cases armed at load; assigned below the gate

test("prose: no authored file carries a British spelling from localization-§5's published list",
function()
    local rules = consumerRules()
    local opts = options()
    if not REGISTERED and #allNarrowings(rules, opts.exempt) > 0 then
        fail("prose gate: a narrowing was declared after this suite loaded, so its refusals and"
            .. " disclosure never registered; set Kit.prose and the waiver file before Kit.run", 2)
    end

    local hits = collect(scannedPaths(rules, opts.exempt), function(path)
        local fh = io.open(path, "r")
        if not fh then
            fail("prose gate: git tracks " .. path .. " but it cannot be opened", 3)
        end
        local body = fh:read("*a") or ""
        fh:close()
        return body
    end, validateWaived(rules.waived))

    if #hits > 0 then
        -- Name every one rather than the first: these arrive a whole commit at a time, and
        -- clearing them a red run at a time is the slowest way to learn how many there were.
        fail(#hits .. " line(s) of authored text carry a British spelling (localization-§5). US "
            .. "English is the source dialect: WoW's own API is US-spelled, so a British-spelled "
            .. "identifier sits one letter from the Blizzard symbol beside it and a `grep -r color` "
            .. "silently misses half its call sites. Correct each, and if the spelling is a locale "
            .. "KEY move every locales/*.lua file and every call site in the same change. If it is "
            .. "game data or a library's field name, waive it in tests/prose_waivers.lua's `waived` "
            .. "table, per file AND per word, with the reason beside it. If EVERY hit in a file is "
            .. "there because a script generated the file, nothing loads it and .pkgmeta keeps it "
            .. "out of the packaged zip, name it in `Kit.prose.exempt` in tests/run.lua instead -- "
            .. "all three conditions, and a generated file that SHIPS is not exempt. NOT a way out "
            .. "is skipDirs or skipFiles: those face the same two refusals, over what they "
            .. "suppress as well as how they are written:\n          "
            .. table.concat(hits, "\n          "), 2)
    end
end)

test("prose: the gate carries localization-§5's two lists whole, and nothing of its own", function()
    if #BRITISH ~= PUBLISHED_BRITISH or #ALLOWED ~= PUBLISHED_ALLOWED then
        fail(string.format("the copied lists are %d BRITISH and %d ALLOWED entries; "
            .. "localization-§5 publishes %d and %d. A gate carrying a subset is the second "
            .. "anti-pattern stacked on the first (#46, testing-§12): it reads as coverage and "
            .. "provides none. Re-copy both blocks whole",
            #BRITISH, #ALLOWED, PUBLISHED_BRITISH, PUBLISHED_ALLOWED), 2)
    end

    -- The section's prose says an allowance is a correct US word that CONTAINS a British substring,
    -- and two of the published thirty-three do not: `syntheses` and `emphases` are the plurals of
    -- `synthesis` and `emphasis`, and neither plural contains its own entry. So that containment
    -- rule is described here rather than asserted. A gate that reddens on the list it is required to
    -- copy whole gets deleted rather than obeyed, and the divergence is the standard's to settle.

    -- Lowercase, because the scan lowercases the line and compares literally. An upper-case entry
    -- would never match anything and would sit in the list looking like coverage.
    local shouty = {}
    for _, entry in ipairs(BRITISH) do
        if entry ~= entry:lower() then shouty[#shouty + 1] = entry end
    end
    if #shouty > 0 then
        fail("BRITISH entries that are not lowercase, and therefore match nothing: "
            .. table.concat(shouty, ", "), 2)
    end
end)

-- ---------------------------------------------------------------------------
-- The carve-out's own three cases, registered only where a carve-out exists
-- ---------------------------------------------------------------------------
--
-- Nothing below registers in a repository that declared no narrowing of its own -- no
-- `Kit.prose.exempt` in the runner and no `skipDirs` or `skipFiles` in the waiver file. There is
-- nothing to disclose and nothing to refuse there, and three standing skips saying so every run
-- would be noise a reader learns to scroll past. The logic is proved everywhere all the same, by
-- the fixture-driven self-tests at the foot of this file. BOTH CHANNELS ARM THESE CASES: keyed on
-- `Kit.prose.exempt` alone, the one repository that narrows the gate through the waiver file and
-- not the runner registered none of the three.
--
-- Read at load: the disclosure case's NAME carries its figures, fixed at registration. A narrowing
-- arriving later (a later suite writing `Kit.prose`) finds none armed, so the gate refuses it.

-- Whether to register at all -- and ONLY that. Everything below re-reads the live tables, because
-- the gate above reads them live too and a disclosure describing a different set from the one the
-- gate applied would be worse than none. A LIST THAT CANNOT BE READ REGISTERS RATHER THAN
-- VANISHING: a waiver file that does not load, or a `Kit.prose` that is not a table, would
-- otherwise take the count to nothing and silently retire the three cases with it.
REGISTERED = (function()
    local ok, count = pcall(function() return #allNarrowings(consumerRules(), declared()) end)
    return (not ok) or count > 0
end)()

--- The narrowing's reach: the resolved coverage set, how many tracked authored files it suppressed
--- between them, and how many this gate would otherwise have read. Measured through `filterPaths`
--- twice -- once with everything this repository declared, once with localization-§5's published
--- exclusions alone -- so the figures are the gate's own arithmetic and the paths named are
--- resolved against the same `all` that arithmetic counts.
local function narrowingReach()
    local rules, entries = consumerRules(), declared()
    local tracked = trackedPaths()
    local kitFiles, kitDirs = kitExclusionSets()
    local skipFiles, skipDirs = exclusionSets(rules)
    local all = filterPaths(tracked, kitFiles, kitDirs, {})
    local kept = filterPaths(tracked, skipFiles, skipDirs, resolveExempt(entries, tracked))
    return coverageOf(allNarrowings(rules, entries), all), #all - #kept, #all
end

--- The one resolved coverage set, read live, which both refusals below run over.
local function liveCoverage() return (narrowingReach()) end

--- The disclosure, as one line, or nil if the repository could not be read while loading.
local function reachLine()
    local ok, coverage, suppressed, total = pcall(narrowingReach)
    if not ok then return nil end
    return suppressed .. " of " .. total .. " tracked authored file(s), by: "
        .. coverageSummary(coverage)
end

if REGISTERED then

    -- Registered under the reading taken at load. A run that cannot reach git says so instead of
    -- claiming a figure, and the gate above fails on the same blindness a moment later.
    local DISCLOSED = reachLine()

    test("prose: the exclusions this repository declared suppressed "
        .. (DISCLOSED or "an unreadable number of files"), function()
        local now = reachLine()
        if now == nil then narrowingReach() end  -- re-raise the real reason, not an equality miss
        Kit.assertEqual(now, DISCLOSED,
            "the PASS line above is this run's disclosure of how far this repository narrowed the "
            .. "prose gate, by which entries and over which files, and a reader of a green suite "
            .. "has nothing else to go on. It is written into the case name when the suite loads "
            .. "and measured again here, so a runner or a waiver file that changes between the two "
            .. "reddens rather than printing a narrowing that is not the one applied")
    end)

    test("prose: no path this repository narrows the gate by is loaded by a TOC", function()
        local loaded, tocs = tocLoadedPaths()
        if tocs == 0 then
            Kit.skip("this repository tracks no .toc, so it packages no addon the client loads and "
                .. "localization-§5's LOADED BY NOTHING condition has no TOC to be read off. A "
                .. "library repository or a documentation repository is the normal case. What is "
                .. "left of the condition -- a dofile, a runtime reader -- is the auditor's, "
                .. "exactly as GENERATED RATHER THAN AUTHORED always is")
        end

        local bad = narrowingsLoadedByToc(liveCoverage(), loaded)
        if #bad > 0 then
            fail(#bad .. " path(s) this repository narrows the prose gate by are loaded by its own "
                .. "TOC: " .. table.concat(bad, "; ") .. ". No list may take a file the client "
                .. "loads out of this scan: localization-§5's carve-out is for generated data "
                .. "LOADED BY NOTHING, and its named exclusions are for text that is not this "
                .. "repository's English at all. A file the TOC loads is inside the packaged "
                .. "payload, so its spellings reach a player's screen, which is the one thing this "
                .. "rule exists to prevent -- in whichever list it is written, this is the "
                .. "whole-file waiver localization-§5 forbids. Correct the spelling, or waive it in "
                .. "tests/prose_waivers.lua's `waived` table, per file AND per word, with the "
                .. "reason beside it: the one narrowing these refusals do not police, because it "
                .. "cannot hide a spelling it did not name", 2)
        end
    end)

    test("prose: every path this repository narrows the gate by is one .pkgmeta keeps out of the zip",
    function()
        local body = readFile(".pkgmeta")
        if body == nil then
            local _, tocs = tocLoadedPaths()
            if tocs == 0 then
                Kit.skip("this repository has no .pkgmeta and tracks no .toc, so nothing in it is "
                    .. "packaged for a player to download and localization-§5's EXCLUDED FROM WHAT "
                    .. "A PLAYER DOWNLOADS condition has no packaging manifest to be read off. A "
                    .. "library repository or a documentation repository is the normal case")
            end
            fail("this repository packages an addon -- it tracks a .toc -- and has no .pkgmeta at "
                .. "its root, so the packager ships the working tree whole and every path this "
                .. "repository narrows the prose gate by is inside what a player downloads. "
                .. "localization-§5 excludes a file from this gate only when its spellings cannot "
                .. "reach a player; write the .pkgmeta ignore entries that keep them out, or stop "
                .. "narrowing the gate by them", 2)
        end

        local bad, unmatched = narrowingsNotIgnored(liveCoverage(), pkgmetaIgnores(body))
        if #bad > 0 then
            fail(#bad .. " path(s) this repository narrows the prose gate by are not ones .pkgmeta "
                .. "keeps out of the zip, so the packager puts them in what a player downloads: "
                .. table.concat(bad, ", ") .. ". Each is refused as written, or for a packaged "
                .. "file it covers without naming -- a narrowing is what it SUPPRESSES, and a "
                .. "prefix reaches past the folder .pkgmeta blessed. All three lists stand on the "
                .. "same condition: localization-§5 excludes a file only when its spellings cannot "
                .. "reach a player's screen, and a generated file that SHIPS is not exempt. Add "
                .. "the ignore entry, narrow the entry until it covers only what the packager "
                .. "drops, correct the spelling, or waive it in tests/prose_waivers.lua's "
                .. "`waived` table, per file AND per word, with the reason beside it", 2)
        end

        if #unmatched > 0 then
            fail(#unmatched .. " path(s) this repository narrows the prose gate by match nothing "
                .. "this gate would otherwise read: " .. table.concat(unmatched, ", ") .. ". The "
                .. "problem is the spelling rather than the packaging, which is why this says so "
                .. "instead of sending you to .pkgmeta: git writes forward slashes, no leading "
                .. "`./`, no trailing `/`, and is case-sensitive. A narrowing that suppresses "
                .. "nothing still reads as coverage of something: correct it, or delete it", 2)
        end
    end)

end

-- ---------------------------------------------------------------------------
-- The self-tests
-- ---------------------------------------------------------------------------
--
-- They ship with the gate, below it, and they are pure: they drive the functions the gate itself
-- runs over fixtures in memory, touching neither git nor the disk. Here rather than only in the
-- library repo's own suite for the reason the cap gate's are: a vendored gate whose logic is tested
-- only upstream can rot in place through a re-vendor.
--
-- The fixture bodies below quote British spellings on purpose, which is safe in both homes this
-- file has: in the kit it is `testkit/test_prose.lua`, exempt by name from the library repo's own
-- shipped-payload gate, and in a consumer it is under the `tests/_kit/` prefix this gate skips.

local FIXTURE = {
    ["GlobalStrings/GlobalStrings.lua"]     = 'ERR_DUEL_X = "Duel cancelled.";',
    ["GlobalStrings/GlobalStrings_018.lua"] = 'NPEV2_SELL_GREY_ITEMS = "grey items";',
    ["GlobalStringsNotes.md"]               = "The dump is regenerated, not coloured by hand.",
    ["core/Frame.lua"]                      = "-- centre the frame",
    ["media/logo.png"]                      = "",
}
local FIXTURE_PATHS = {
    "GlobalStrings/GlobalStrings.lua", "GlobalStrings/GlobalStrings_018.lua",
    "GlobalStringsNotes.md", "core/Frame.lua", "media/logo.png",
}
local NO_SKIP_FILES, NO_SKIP_DIRS = {}, {}

--- The gate's own three steps, run over the fixture: resolve, filter, collect.
local function scanFixture(exempt)
    local paths = filterPaths(FIXTURE_PATHS, NO_SKIP_FILES, NO_SKIP_DIRS,
        resolveExempt(exempt, FIXTURE_PATHS))
    return paths, collect(paths, function(path) return FIXTURE[path] end, {})
end

test("prose self-test: the carve-out suppresses the named generated folder, and only it", function()
    local _, before = scanFixture(nil)
    Kit.assertEqual(#before, 4, "with no carve-out every authored fixture file is read and reported")

    local paths, after = scanFixture{ "GlobalStrings/" }
    Kit.assertEqual(#after, 2, "the two generated files go quiet and the other two do not")
    Kit.assertEqual(table.concat(after, " | "),
        "GlobalStringsNotes.md:1 - colour | core/Frame.lua:1 - centre",
        "and the two that remain are named with their line and their word")

    for _, path in ipairs(paths) do
        Kit.assertFalse(path:sub(1, #"GlobalStrings/") == "GlobalStrings/",
            "an exempt file is dropped before it is read, not filtered after: " .. path)
    end
end)

test("prose self-test: a path the carve-out does not name is not covered by one that looks like it",
function()
    -- `GlobalStringsNotes.md` is the whole point of the folder form comparing against
    -- `entry .. "/"`. A plain prefix match would swallow it, and the file a repository actually
    -- writes by hand would be the one that stopped being checked.
    for _, entry in ipairs{ "GlobalStrings/", "GlobalStrings" } do
        local set = resolveExempt({ entry }, FIXTURE_PATHS)
        Kit.assertTrue(set["GlobalStrings/GlobalStrings.lua"], "the dump is covered by " .. entry)
        Kit.assertTrue(set["GlobalStrings/GlobalStrings_018.lua"], "and every chunk beside it")
        Kit.assertFalse(set["GlobalStringsNotes.md"] == true,
            "and NOT the sibling that merely starts with it, written as `" .. entry .. "`")
        Kit.assertFalse(set["core/Frame.lua"] == true, "nor anything else in the tree")
    end

    local _, hits = scanFixture{ "GlobalStrings/GlobalStrings.lua" }
    Kit.assertEqual(#hits, 3, "naming one file exempts that file and leaves its chunks scanned")
    Kit.assertTrue(hits[1]:find("GlobalStrings_018", 1, true) ~= nil,
        "the unnamed chunk still reddens on the same spelling: " .. hits[1])

    local exact = resolveExempt({ ["core/Frame.lua"] = true }, FIXTURE_PATHS)
    Kit.assertTrue(exact["core/Frame.lua"], "the map form names one path")
    Kit.assertFalse(exact["GlobalStringsNotes.md"] == true, "and only that one")
end)

test("prose self-test: a carve-out that is not a set of path strings is a failure, not a silence",
function()
    Kit.assertError(function() resolveExempt("GlobalStrings/", FIXTURE_PATHS) end,
        "a bare string is the shape a runner reaches for first, and it would exempt nothing")
    Kit.assertError(function() resolveExempt({ 17 }, FIXTURE_PATHS) end,
        "an entry that is not a string cannot name a tracked path")

    -- Stale is not silent, and is deliberately NOT a failure: the file an entry named is gone, so
    -- there is nothing left for it to hide. Same call `Kit.layoutCap.exempt` makes.
    local stale = resolveExempt({ "Retired/" }, FIXTURE_PATHS)
    Kit.assertNil(next(stale), "an entry matching nothing resolves to an empty set and passes")

    -- And the table it arrives in: `Kit.prose = "GlobalStrings/"` is a mistake that would
    -- otherwise read as a repository with no generated data at all. DRIVEN OVER FIXTURE TABLES,
    -- AND `Kit.prose` IS NEVER TOUCHED -- the first draft of these three lines saved the live
    -- table, set a bad value, RESTORED IT and only then read it back, so the last assertion landed
    -- on the consumer's own carve-out and shipped permanently red there.
    Kit.assertError(function() validateOptions("GlobalStrings/") end,
        "Kit.prose set to something other than a table is a failure")
    Kit.assertNil(next(validateOptions(nil).exempt or {}),
        "and an absent Kit.prose is the normal case: no carve-out, no complaint")
    Kit.assertEqual(validateOptions{ exempt = { "GlobalStrings/" } }.exempt[1], "GlobalStrings/",
        "while a declared one is handed back whole")
end)

-- The two conditions the repository root answers, driven over the bodies the two repositories that
-- settled this question actually ship. They are fixtures, not reads: this library repo has no
-- `.toc`, no `.pkgmeta` and no carve-out, so a case reading its own surroundings would prove
-- nothing anywhere -- the mistake this file shipped once already, in the case above.

local PRETTYCHAT_TOC = table.concat({
    "## Interface: 120100", "## Title: Fixture", "## SavedVariables: PrettyChatDB", "",
    "# Libraries (must load first)", "libs\\LibStub\\LibStub.lua", "libs\\LibKa0s\\LibKa0s.xml",
    "", "# Locales", "locales\\enUS.lua", "core\\EnvSetup.lua",
}, "\n")

local PRETTYCHAT_PKGMETA = table.concat({
    "package-as: PrettyChat", "", "enable-nolib-creation: no", "",
    "ignore:",
    "  - .luacheckrc",
    "  - docs        # holds docs/audits/ and docs/reviews/ too - all dev-only",
    "  - tests", '  - "*.bak"', "",
    "  # Generated reference data - the WHOLE folder, source dump, 26 chunks and all.",
    "  - GlobalStrings", "", "  - media/logos/*.png", "",
    "move-folders:", "  PrettyChat/nothing: nothing",
}, "\n")

local WHATGROUP_TOC = table.concat({
    "## Interface: 120100", "core\\Util.lua", "core\\Compat.lua",
    "# The LibKa0s-Env seam. After Compat, and before the two files that read the TOC.",
    "core\\EnvSetup.lua", "core\\Database.lua", "core\\WhatGroup.lua",
}, "\n")

local WHATGROUP_PKGMETA = table.concat({
    "package-as: WhatGroup", "", "ignore:", "  - .luacheckrc",
    "  - docs        # includes docs/audits and docs/reviews", "  - tests", "  - CLAUDE.md",
}, "\n")

test("prose self-test: a TOC's file lines are read as paths, and its directives and comments are not",
function()
    local loaded = tocLoads("PrettyChat.toc", PRETTYCHAT_TOC)
    Kit.assertEqual(#loaded, 4, "four file lines, and neither the three directives, the two "
        .. "comments nor the two blank lines")

    Kit.assertEqual(loaded[1].path, "libs/LibStub/LibStub.lua",
        "the client's backslashes are read as the separators they are")
    Kit.assertEqual(loaded[1].line, 6, "and the line is the one a reader will open the TOC to")
    Kit.assertEqual(loaded[1].toc, "PrettyChat.toc", "named with the TOC it came from")
    Kit.assertEqual(loaded[4].path, "core/EnvSetup.lua", "and the last file line is read too")

    -- A vendored library's TOC names ITS files: resolved against the repository root instead, a
    -- line reading `core\\Foo.lua` in libs/Bar/Bar.toc would claim this repository's core/Foo.lua
    -- is loaded and refuse an exemption over it.
    local nested = tocLoads("libs/Bar/Bar.toc", "core\\Foo.lua")
    Kit.assertEqual(nested[1].path, "libs/Bar/core/Foo.lua",
        "a nested TOC's lines resolve against the folder the TOC sits in")
end)

test("prose self-test: a .pkgmeta's ignore block is read, and the keys around it are not", function()
    local ignores = pkgmetaIgnores(PRETTYCHAT_PKGMETA)
    Kit.assertEqual(table.concat(ignores, ", "),
        ".luacheckrc, docs, tests, *.bak, GlobalStrings, media/logos/*.png",
        "every entry, with its trailing comment and its quotes taken off, and in file order")

    -- An indented comment and a blank line are ordinary inside these blocks and neither closes it.
    -- A key at column zero does, or `move-folders:` below would be read as two more ignores.
    for _, entry in ipairs(ignores) do
        Kit.assertFalse(entry:find("move%-folders") ~= nil,
            "a sibling key at column zero closes the block: " .. entry)
        Kit.assertFalse(entry:find("nothing", 1, true) ~= nil,
            "and nothing nested under that key is read as an ignore: " .. entry)
    end

    Kit.assertEqual(#pkgmetaIgnores("package-as: X\n"), 0,
        "a .pkgmeta with no ignore block yields no entries rather than failing")
end)

test("prose self-test: an ignore entry covers a path exactly, by folder, and by wildcard", function()
    Kit.assertTrue(ignoreCovers("GlobalStrings", "GlobalStrings/"),
        "the folder form a runner writes is covered by the bare name .pkgmeta writes")
    Kit.assertTrue(ignoreCovers("GlobalStrings", "GlobalStrings/GlobalStrings_018.lua"),
        "and so is a file inside it")
    Kit.assertFalse(ignoreCovers("GlobalStrings", "GlobalStringsNotes.md"),
        "and NOT the sibling that merely starts with the same letters")
    Kit.assertTrue(ignoreCovers("docs", "docs/data-flow.md"), "a folder covers what is under it")
    Kit.assertFalse(ignoreCovers("docs", "docsite/index.md"), "and nothing beside it")

    Kit.assertTrue(ignoreCovers("*.bak", "core/Frame.lua.bak"),
        "`*.bak` is written to mean a backup anywhere, so it is matched on the basename too")
    Kit.assertTrue(ignoreCovers("media/logos/*.png", "media/logos/logo.png"),
        "and a folder-scoped wildcard on the whole path")
    Kit.assertFalse(ignoreCovers("media/logos/*.png", "media/logos/logo.tga"),
        "which still refuses the extension it does not name")
end)

--- What the two fixture repositories track, as `filterPaths` would leave it: the universe every
--- narrowing below is resolved against, exactly as the gate resolves one against the live tree.
local FIXTURE_TRACKED = {
    "GlobalStrings/GlobalStrings.lua", "GlobalStringsNotes.md", "core/Compat.lua",
    "core/EnvSetup.lua", "core/Util.lua", "core/WhatGroup.lua", "docs/data-flow.md",
    "docs/spell-research/2026/notes.md", "locales/enUS.lua", "tests/run.lua",
}

--- The two refusals' input, built exactly as the gate builds it: a fixture carve-out and a fixture
--- waiver table, resolved against a fixture tracked set. Neither `Kit.prose` nor a file on disk is
--- touched by any case below.
local function coverOf(exempt, rules, paths)
    return coverageOf(allNarrowings(rules, exempt), paths or FIXTURE_TRACKED)
end

test("prose self-test: the carve-out admits a generated dump and refuses a file the TOC loads",
function()
    -- PrettyChat's, the case the carve-out exists for: generated chunks, no TOC line near them,
    -- and `- GlobalStrings` in the packaging manifest.
    local legit = coverOf({ "GlobalStrings/" })
    Kit.assertEqual(#narrowingsLoadedByToc(legit, tocLoads("PrettyChat.toc", PRETTYCHAT_TOC)), 0,
        "nothing in the TOC loads the dump")
    Kit.assertEqual(#narrowingsNotIgnored(legit, pkgmetaIgnores(PRETTYCHAT_PKGMETA)), 0,
        "and .pkgmeta keeps it out of the zip, so both gated conditions pass")

    -- WhatGroup's, the whole-file waiver wearing the carve-out's name, wired exactly as it was
    -- when it took that repository's gate green over five real hits, two of them in a TOC-loaded
    -- file. If either refusal is ever reverted, THIS case goes red.
    local abuse = coverOf({ "core/WhatGroup.lua", "docs/data-flow.md", "tests/" })
    local byToc = narrowingsLoadedByToc(abuse, tocLoads("WhatGroup.toc", WHATGROUP_TOC))
    Kit.assertEqual(#byToc, 1, "one of the three is loaded by the TOC")
    Kit.assertTrue(byToc[1]:find("core/WhatGroup.lua", 1, true) == 1,
        "and it is the shipped source file: " .. byToc[1])
    Kit.assertTrue(byToc[1]:find("[" .. SOURCE_EXEMPT .. "]", 1, true) ~= nil,
        "named with the list it was written in: " .. byToc[1])
    Kit.assertTrue(byToc[1]:find("line 7 of WhatGroup.toc", 1, true) ~= nil,
        "and with the TOC line that loads it: " .. byToc[1])

    local byPkg = narrowingsNotIgnored(abuse, pkgmetaIgnores(WHATGROUP_PKGMETA))
    Kit.assertEqual(table.concat(byPkg, ", "), "core/WhatGroup.lua [" .. SOURCE_EXEMPT .. "]",
        "and the same file is the one .pkgmeta does not keep out of the zip, while docs/ and "
        .. "tests/ are ignored and clear this condition")

    -- The third condition is untouched by both: `docs/data-flow.md` is authored prose, not in the
    -- TOC and ignored by .pkgmeta, so it passes every check a gate can make and is refused by a
    -- reader or not at all -- the cap gate's boundary too.
    Kit.assertEqual(#narrowingsLoadedByToc(coverOf({ "docs/data-flow.md" }),
        tocLoads("WhatGroup.toc", WHATGROUP_TOC)), 0, "the gate has no opinion about it")
    Kit.assertEqual(#narrowingsNotIgnored(coverOf({ "docs/data-flow.md" }),
        pkgmetaIgnores(WHATGROUP_PKGMETA)), 0, "under either gated condition")
end)

test("prose self-test: a waiver-file exclusion meets the same two refusals as the carve-out",
function()
    -- The older, wider channel, wired to hide exactly what the carve-out was stopped from hiding:
    -- WhatGroup's shipped, TOC-loaded source file, written in the other list.
    local viaFile = coverOf(nil, { skipFiles = { ["core/WhatGroup.lua"] = true } })
    local byToc = narrowingsLoadedByToc(viaFile, tocLoads("WhatGroup.toc", WHATGROUP_TOC))
    Kit.assertEqual(#byToc, 1, "skipFiles is read against the TOC too, and this file is on it")
    Kit.assertTrue(byToc[1]:find("[" .. SOURCE_SKIPFILES .. "]", 1, true) ~= nil,
        "named with the list it was written in, so the reader opens the right file: " .. byToc[1])
    Kit.assertTrue(byToc[1]:find("line 7 of WhatGroup.toc", 1, true) ~= nil,
        "and with the TOC line that loads it, exactly as the carve-out's refusal reads: "
        .. byToc[1])
    Kit.assertEqual(table.concat(narrowingsNotIgnored(viaFile,
        pkgmetaIgnores(WHATGROUP_PKGMETA)), ", "),
        "core/WhatGroup.lua [" .. SOURCE_SKIPFILES .. "]",
        "and .pkgmeta does not keep it out of the zip either")

    -- The same over skipDirs, which reaches the file through the folder above it.
    local viaDir = coverOf(nil, { skipDirs = { "core/" } })
    Kit.assertEqual(#narrowingsLoadedByToc(viaDir, tocLoads("WhatGroup.toc", WHATGROUP_TOC)), 1,
        "a skipDirs entry is refused on the first TOC line it covers")
    Kit.assertEqual(table.concat(narrowingsNotIgnored(viaDir,
        pkgmetaIgnores(WHATGROUP_PKGMETA)), ", "), "core/ [" .. SOURCE_SKIPDIRS .. "]",
        "and .pkgmeta ignores docs, tests and CLAUDE.md, not the source folder")

    -- And the legitimate shape still passes: AuraMaster's frozen dated store, which is what
    -- `skipDirs` is for. Generated on the day, no TOC line near it, and `- docs` in the manifest.
    local frozen = coverOf(nil, { skipDirs = { "docs/spell-research/" } })
    Kit.assertEqual(#narrowingsLoadedByToc(frozen, tocLoads("WhatGroup.toc", WHATGROUP_TOC)), 0,
        "a dated bundle under docs/ is loaded by no TOC line")
    Kit.assertEqual(#narrowingsNotIgnored(frozen, pkgmetaIgnores(WHATGROUP_PKGMETA)), 0,
        "and `- docs` keeps the whole tree out of the zip, so it clears both conditions")
end)

test("prose self-test: each list is refused on the matching rule its own scan uses", function()
    local loaded = { { path = "core/Frame.lua", line = 3, toc = "Fixture.toc" } }

    -- skipFiles is an EXACT key in the scan, so it is refused on an exact path and nothing wider.
    local only = { "core/Frame.lua" }
    Kit.assertEqual(#narrowingsLoadedByToc(
        coverOf(nil, { skipFiles = { ["core/"] = true } }, only), loaded), 0,
        "a skipFiles entry naming a folder suppresses nothing, so there is nothing to refuse")
    Kit.assertEqual(#narrowingsLoadedByToc(
        coverOf(nil, { skipFiles = { ["core/Frame.lua"] = true } }, only), loaded), 1,
        "and on the exact path it does suppress, it is refused")

    -- skipDirs is the PLAIN PREFIX `filterPaths` compares, which is wider than the carve-out's
    -- folder form -- deliberately, because the scan is wider there too.
    Kit.assertEqual(#narrowingsLoadedByToc(coverOf(nil, { skipDirs = { "core/Fra" } }, only),
        loaded), 1, "a skipDirs prefix the scan would suppress by is refused by that same prefix")
    Kit.assertEqual(#narrowingsLoadedByToc(coverOf({ "core/Fra" }, nil, only), loaded), 0,
        "while the carve-out's folder form neither reaches that file nor suppresses it")
end)

test("prose self-test: the scan and the refusals read the added exclusions through one reader",
function()
    local rules = { skipDirs = { "docs/frozen/" },
                    skipFiles = { ["docs/vendor-notes.md"] = true } }
    local skipFiles, skipDirs = exclusionSets(rules)
    Kit.assertTrue(skipFiles["docs/vendor-notes.md"], "the scan drops the named file")
    Kit.assertEqual(skipDirs[#skipDirs], "docs/frozen/", "and everything under the named folder")
    Kit.assertTrue(skipFiles["locales/enGB.lua"],
        "localization-§5's own exclusions are still there underneath")

    Kit.assertEqual(coverageSummary(coverOf({ "GlobalStrings/" }, rules, {
            "GlobalStrings/GlobalStrings.lua", "README.md",
            "docs/frozen/2026/a.md", "docs/vendor-notes.md" })),
        "GlobalStrings/ [" .. SOURCE_EXEMPT .. "] (1): GlobalStrings/GlobalStrings.lua; "
        .. "docs/frozen/ [" .. SOURCE_SKIPDIRS .. "] (1): docs/frozen/2026/a.md; "
        .. "docs/vendor-notes.md [" .. SOURCE_SKIPFILES .. "] (1): docs/vendor-notes.md",
        "and one disclosure names all three, sorted, each with the list it came from and with the "
        .. "paths it suppressed under it")

    -- The array form of skipFiles used to suppress NOTHING: `pairs` copied it across key and all,
    -- leaving a numeric key no path lookup could hit. Both forms go through the one reader now.
    local files = exclusionSets{ skipFiles = { "docs/vendor-notes.md" } }
    Kit.assertTrue(files["docs/vendor-notes.md"], "the array form names a file too")

    Kit.assertError(function() exclusionSets{ skipDirs = "docs/frozen/" } end,
        "a bare string would exclude nothing, so it is a failure rather than a silence")
    Kit.assertError(function() exclusionSets{ skipFiles = { 17 } } end,
        "and an entry that is not a string cannot name a tracked path, in this list either")

    -- localization-§5's published exclusions are the BASELINE, not a narrowing this repository
    -- chose: they are not disclosed and not refused, and `libs/` is on every TOC in the collection.
    Kit.assertNil(next(allNarrowings({}, nil)),
        "a repository that added nothing declares no narrowing at all")
end)

test("prose self-test: a narrowing is refused by what it suppresses, not by how it is written",
function()
    -- The hole the one coverage set closes, reproduced. `.pkgmeta` ignores the `tools` FOLDER and
    -- `skipDirs` is an UNANCHORED prefix, so the entry hides the shipped root file beside it while
    -- the entry as written stands blessed. Measured in a throwaway consumer before the fix: 15
    -- passed, 0 failed, both refusals green, and `tools-notes.md` -- two British spellings, inside
    -- the zip -- read by nothing.
    local tracked = { "README.md", "tools-notes.md", "tools/build.lua" }
    local ignores = pkgmetaIgnores("ignore:\n  - docs\n  - tools\n")
    local spill = coverOf(nil, { skipDirs = { "tools" } }, tracked)
    Kit.assertEqual(table.concat(spill[1].paths, ", "), "tools-notes.md, tools/build.lua",
        "the prefix covers the shipped root file as well as the ignored folder")
    local bad = narrowingsNotIgnored(spill, ignores)
    Kit.assertEqual(#bad, 1, "so the entry is refused although .pkgmeta ignores it as written")
    Kit.assertTrue(bad[1]:find("tools-notes.md", 1, true) ~= nil,
        "named by the shipped path it hides, which is the file a reader opens: " .. bad[1])
    Kit.assertEqual(#narrowingsNotIgnored(coverOf(nil, { skipDirs = { "tools/" } }, tracked),
        ignores), 0, "while the anchored spelling covers the ignored folder alone, and passes")

    -- And a narrowing that suppresses nothing is refused for its SPELLING. Sent to `.pkgmeta` it
    -- contradicted the same run's disclosure, which said truthfully that it suppressed nothing.
    local wrong, unmatched = narrowingsNotIgnored(
        coverOf(nil, { skipDirs = { "Tools/" } }, tracked), ignores)
    Kit.assertEqual(table.concat(unmatched, ", "), "Tools/ [" .. SOURCE_SKIPDIRS .. "]",
        "git is case-sensitive, so this entry matches nothing and says THAT")
    Kit.assertEqual(#wrong, 0, "rather than reading as a file the packager ships")
    local stale, none = narrowingsNotIgnored(
        coverOf(nil, { skipDirs = { "tools/gone/" } }, tracked), ignores)
    Kit.assertEqual(#stale + #none, 0,
        "while a stale entry .pkgmeta does cover stays stale rather than silent, and passes")
end)

test("prose self-test: the disclosure names what each entry suppressed, and says when it is bounded",
function()
    local small = coverOf(nil, { skipDirs = { "docs/frozen/" } },
        { "README.md", "docs/frozen/a.md", "docs/frozen/b.md" })
    Kit.assertEqual(coverageSummary(small),
        "docs/frozen/ [" .. SOURCE_SKIPDIRS .. "] (2): docs/frozen/a.md, docs/frozen/b.md",
        "under the bound every suppressed path is named, beneath the entry that suppressed it")

    -- 225 of 228 is the shape that makes naming them all unaffordable, and a truncated list a
    -- reader takes for a complete one is worse than the count on its own.
    local many = { "README.md" }
    for i = 1, 225 do many[#many + 1] = string.format("docs/frozen/%03d.md", i) end
    local line = coverageSummary(coverOf(nil, { skipDirs = { "docs/frozen/" } }, many))
    Kit.assertTrue(line:find("(225)", 1, true) ~= nil, "the count is the whole truth: " .. line)
    Kit.assertTrue(line:find("and 222 more (list bounded)", 1, true) ~= nil,
        "and the list that is not says out loud that it was cut short: " .. line)
    Kit.assertTrue(coverageSummary(coverOf(nil, { skipDirs = { "docs/gone/" } },
        { "README.md" })):find("(0): nothing", 1, true) ~= nil,
        "an entry that suppressed nothing says so rather than reading as coverage")
end)

test("prose self-test: a malformed waived is a failure, not a silence", function()
    -- The third key in the same table, and the silence `skipFiles` had just been cured of: the scan
    -- looks a waiver up by PATH and its words up by WORD, so either array form waives nothing at
    -- all. `waived` is still outside the two refusals -- per file AND per word, it cannot hide a
    -- spelling it did not name -- and this is the shape check that leaves it honest.
    Kit.assertError(function() validateWaived("core/Frame.lua") end,
        "a bare string is not a waiver table")
    Kit.assertError(function() validateWaived{ "core/Frame.lua" } end,
        "the array form waives nothing, which is the silence just removed from skipFiles")
    Kit.assertError(function() validateWaived{ ["core/Frame.lua"] = true } end,
        "per file AND per word: a file mapped to `true` is the whole-file waiver 5 forbids")
    Kit.assertError(function() validateWaived{ ["core/Frame.lua"] = { "centre" } } end,
        "and a word list written as an array waives nothing either")
    Kit.assertNil(next(validateWaived(nil)), "absent is the normal case and waives nothing")
    Kit.assertTrue(validateWaived{ ["core/Frame.lua"] = { centre = true } }["core/Frame.lua"].centre,
        "while the shape the docstring shows is handed back whole")
end)
